//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StrawmanApp.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class godzillaCommentsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new godzillaCommentsEntities object using the connection string found in the 'godzillaCommentsEntities' section of the application configuration file.
        /// </summary>
        public godzillaCommentsEntities() : base("name=godzillaCommentsEntities", "godzillaCommentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new godzillaCommentsEntities object.
        /// </summary>
        public godzillaCommentsEntities(string connectionString) : base(connectionString, "godzillaCommentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new godzillaCommentsEntities object.
        /// </summary>
        public godzillaCommentsEntities(EntityConnection connection) : base(connection, "godzillaCommentsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LETTERS_COMMENT_DATA> LETTERS_COMMENT_DATA
        {
            get
            {
                if ((_LETTERS_COMMENT_DATA == null))
                {
                    _LETTERS_COMMENT_DATA = base.CreateObjectSet<LETTERS_COMMENT_DATA>("LETTERS_COMMENT_DATA");
                }
                return _LETTERS_COMMENT_DATA;
            }
        }
        private ObjectSet<LETTERS_COMMENT_DATA> _LETTERS_COMMENT_DATA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MANAGEMENT_LETTERS_MASTER> MANAGEMENT_LETTERS_MASTER
        {
            get
            {
                if ((_MANAGEMENT_LETTERS_MASTER == null))
                {
                    _MANAGEMENT_LETTERS_MASTER = base.CreateObjectSet<MANAGEMENT_LETTERS_MASTER>("MANAGEMENT_LETTERS_MASTER");
                }
                return _MANAGEMENT_LETTERS_MASTER;
            }
        }
        private ObjectSet<MANAGEMENT_LETTERS_MASTER> _MANAGEMENT_LETTERS_MASTER;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_MANAGEMENT_LETTERS> v_WRK_MANAGEMENT_LETTERS
        {
            get
            {
                if ((_v_WRK_MANAGEMENT_LETTERS == null))
                {
                    _v_WRK_MANAGEMENT_LETTERS = base.CreateObjectSet<v_WRK_MANAGEMENT_LETTERS>("v_WRK_MANAGEMENT_LETTERS");
                }
                return _v_WRK_MANAGEMENT_LETTERS;
            }
        }
        private ObjectSet<v_WRK_MANAGEMENT_LETTERS> _v_WRK_MANAGEMENT_LETTERS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_MONTHLY_COMMENTS_DATA> v_WRK_MONTHLY_COMMENTS_DATA
        {
            get
            {
                if ((_v_WRK_MONTHLY_COMMENTS_DATA == null))
                {
                    _v_WRK_MONTHLY_COMMENTS_DATA = base.CreateObjectSet<v_WRK_MONTHLY_COMMENTS_DATA>("v_WRK_MONTHLY_COMMENTS_DATA");
                }
                return _v_WRK_MONTHLY_COMMENTS_DATA;
            }
        }
        private ObjectSet<v_WRK_MONTHLY_COMMENTS_DATA> _v_WRK_MONTHLY_COMMENTS_DATA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_MANAGEMENT_LETTERS_DATA> v_WRK_MANAGEMENT_LETTERS_DATA
        {
            get
            {
                if ((_v_WRK_MANAGEMENT_LETTERS_DATA == null))
                {
                    _v_WRK_MANAGEMENT_LETTERS_DATA = base.CreateObjectSet<v_WRK_MANAGEMENT_LETTERS_DATA>("v_WRK_MANAGEMENT_LETTERS_DATA");
                }
                return _v_WRK_MANAGEMENT_LETTERS_DATA;
            }
        }
        private ObjectSet<v_WRK_MANAGEMENT_LETTERS_DATA> _v_WRK_MANAGEMENT_LETTERS_DATA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CHANNEL_MASTER> CHANNEL_MASTER
        {
            get
            {
                if ((_CHANNEL_MASTER == null))
                {
                    _CHANNEL_MASTER = base.CreateObjectSet<CHANNEL_MASTER>("CHANNEL_MASTER");
                }
                return _CHANNEL_MASTER;
            }
        }
        private ObjectSet<CHANNEL_MASTER> _CHANNEL_MASTER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LETTERS_COMMENT_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLETTERS_COMMENT_DATA(LETTERS_COMMENT_DATA lETTERS_COMMENT_DATA)
        {
            base.AddObject("LETTERS_COMMENT_DATA", lETTERS_COMMENT_DATA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MANAGEMENT_LETTERS_MASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMANAGEMENT_LETTERS_MASTER(MANAGEMENT_LETTERS_MASTER mANAGEMENT_LETTERS_MASTER)
        {
            base.AddObject("MANAGEMENT_LETTERS_MASTER", mANAGEMENT_LETTERS_MASTER);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_MANAGEMENT_LETTERS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_MANAGEMENT_LETTERS(v_WRK_MANAGEMENT_LETTERS v_WRK_MANAGEMENT_LETTERS)
        {
            base.AddObject("v_WRK_MANAGEMENT_LETTERS", v_WRK_MANAGEMENT_LETTERS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_MONTHLY_COMMENTS_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_MONTHLY_COMMENTS_DATA(v_WRK_MONTHLY_COMMENTS_DATA v_WRK_MONTHLY_COMMENTS_DATA)
        {
            base.AddObject("v_WRK_MONTHLY_COMMENTS_DATA", v_WRK_MONTHLY_COMMENTS_DATA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_MANAGEMENT_LETTERS_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_MANAGEMENT_LETTERS_DATA(v_WRK_MANAGEMENT_LETTERS_DATA v_WRK_MANAGEMENT_LETTERS_DATA)
        {
            base.AddObject("v_WRK_MANAGEMENT_LETTERS_DATA", v_WRK_MANAGEMENT_LETTERS_DATA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CHANNEL_MASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCHANNEL_MASTER(CHANNEL_MASTER cHANNEL_MASTER)
        {
            base.AddObject("CHANNEL_MASTER", cHANNEL_MASTER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="CHANNEL_MASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHANNEL_MASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CHANNEL_MASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CHANNEL_MASTER CreateCHANNEL_MASTER(global::System.Decimal id)
        {
            CHANNEL_MASTER cHANNEL_MASTER = new CHANNEL_MASTER();
            cHANNEL_MASTER.ID = id;
            return cHANNEL_MASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="LETTERS_COMMENT_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LETTERS_COMMENT_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LETTERS_COMMENT_DATA object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static LETTERS_COMMENT_DATA CreateLETTERS_COMMENT_DATA(global::System.Decimal id)
        {
            LETTERS_COMMENT_DATA lETTERS_COMMENT_DATA = new LETTERS_COMMENT_DATA();
            lETTERS_COMMENT_DATA.ID = id;
            return lETTERS_COMMENT_DATA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LETTER_ID
        {
            get
            {
                return _LETTER_ID;
            }
            set
            {
                OnLETTER_IDChanging(value);
                ReportPropertyChanging("LETTER_ID");
                _LETTER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LETTER_ID");
                OnLETTER_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _LETTER_ID;
        partial void OnLETTER_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnLETTER_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String USER
        {
            get
            {
                return _USER;
            }
            set
            {
                OnUSERChanging(value);
                ReportPropertyChanging("USER");
                _USER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("USER");
                OnUSERChanged();
            }
        }
        private global::System.String _USER;
        partial void OnUSERChanging(global::System.String value);
        partial void OnUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YEAR_PERIOD
        {
            get
            {
                return _YEAR_PERIOD;
            }
            set
            {
                OnYEAR_PERIODChanging(value);
                ReportPropertyChanging("YEAR_PERIOD");
                _YEAR_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YEAR_PERIOD");
                OnYEAR_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _YEAR_PERIOD;
        partial void OnYEAR_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnYEAR_PERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_PERIOD
        {
            get
            {
                return _MONTH_PERIOD;
            }
            set
            {
                OnMONTH_PERIODChanging(value);
                ReportPropertyChanging("MONTH_PERIOD");
                _MONTH_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_PERIOD");
                OnMONTH_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_PERIOD;
        partial void OnMONTH_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_PERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                OnTYPEChanging(value);
                ReportPropertyChanging("TYPE");
                _TYPE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TYPE");
                OnTYPEChanged();
            }
        }
        private global::System.String _TYPE;
        partial void OnTYPEChanging(global::System.String value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE
        {
            get
            {
                return _DATE;
            }
            set
            {
                OnDATEChanging(value);
                ReportPropertyChanging("DATE");
                _DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE");
                OnDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE;
        partial void OnDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATEChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="MANAGEMENT_LETTERS_MASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MANAGEMENT_LETTERS_MASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MANAGEMENT_LETTERS_MASTER object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static MANAGEMENT_LETTERS_MASTER CreateMANAGEMENT_LETTERS_MASTER(global::System.Decimal id)
        {
            MANAGEMENT_LETTERS_MASTER mANAGEMENT_LETTERS_MASTER = new MANAGEMENT_LETTERS_MASTER();
            mANAGEMENT_LETTERS_MASTER.ID = id;
            return mANAGEMENT_LETTERS_MASTER;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CHANNEL
        {
            get
            {
                return _CHANNEL;
            }
            set
            {
                OnCHANNELChanging(value);
                ReportPropertyChanging("CHANNEL");
                _CHANNEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHANNEL");
                OnCHANNELChanged();
            }
        }
        private Nullable<global::System.Decimal> _CHANNEL;
        partial void OnCHANNELChanging(Nullable<global::System.Decimal> value);
        partial void OnCHANNELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MAIN_GROUP
        {
            get
            {
                return _MAIN_GROUP;
            }
            set
            {
                OnMAIN_GROUPChanging(value);
                ReportPropertyChanging("MAIN_GROUP");
                _MAIN_GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAIN_GROUP");
                OnMAIN_GROUPChanged();
            }
        }
        private Nullable<global::System.Decimal> _MAIN_GROUP;
        partial void OnMAIN_GROUPChanging(Nullable<global::System.Decimal> value);
        partial void OnMAIN_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GROUP
        {
            get
            {
                return _GROUP;
            }
            set
            {
                OnGROUPChanging(value);
                ReportPropertyChanging("GROUP");
                _GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GROUP");
                OnGROUPChanged();
            }
        }
        private Nullable<global::System.Decimal> _GROUP;
        partial void OnGROUPChanging(Nullable<global::System.Decimal> value);
        partial void OnGROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CHANNEL_GROUP
        {
            get
            {
                return _CHANNEL_GROUP;
            }
            set
            {
                OnCHANNEL_GROUPChanging(value);
                ReportPropertyChanging("CHANNEL_GROUP");
                _CHANNEL_GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHANNEL_GROUP");
                OnCHANNEL_GROUPChanged();
            }
        }
        private Nullable<global::System.Decimal> _CHANNEL_GROUP;
        partial void OnCHANNEL_GROUPChanging(Nullable<global::System.Decimal> value);
        partial void OnCHANNEL_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNTRY
        {
            get
            {
                return _COUNTRY;
            }
            set
            {
                OnCOUNTRYChanging(value);
                ReportPropertyChanging("COUNTRY");
                _COUNTRY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COUNTRY");
                OnCOUNTRYChanged();
            }
        }
        private global::System.String _COUNTRY;
        partial void OnCOUNTRYChanging(global::System.String value);
        partial void OnCOUNTRYChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="v_WRK_MANAGEMENT_LETTERS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_MANAGEMENT_LETTERS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_MANAGEMENT_LETTERS object.
        /// </summary>
        /// <param name="gROUP_ID">Initial value of the GROUP_ID property.</param>
        public static v_WRK_MANAGEMENT_LETTERS Createv_WRK_MANAGEMENT_LETTERS(global::System.Decimal gROUP_ID)
        {
            v_WRK_MANAGEMENT_LETTERS v_WRK_MANAGEMENT_LETTERS = new v_WRK_MANAGEMENT_LETTERS();
            v_WRK_MANAGEMENT_LETTERS.GROUP_ID = gROUP_ID;
            return v_WRK_MANAGEMENT_LETTERS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ID;
        partial void OnIDChanging(Nullable<global::System.Int64> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUP_ID
        {
            get
            {
                return _GROUP_ID;
            }
            set
            {
                if (_GROUP_ID != value)
                {
                    OnGROUP_IDChanging(value);
                    ReportPropertyChanging("GROUP_ID");
                    _GROUP_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GROUP_ID");
                    OnGROUP_IDChanged();
                }
            }
        }
        private global::System.Decimal _GROUP_ID;
        partial void OnGROUP_IDChanging(global::System.Decimal value);
        partial void OnGROUP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNTRY
        {
            get
            {
                return _COUNTRY;
            }
            set
            {
                OnCOUNTRYChanging(value);
                ReportPropertyChanging("COUNTRY");
                _COUNTRY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COUNTRY");
                OnCOUNTRYChanged();
            }
        }
        private global::System.String _COUNTRY;
        partial void OnCOUNTRYChanging(global::System.String value);
        partial void OnCOUNTRYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MAIN_NAME
        {
            get
            {
                return _MAIN_NAME;
            }
            set
            {
                OnMAIN_NAMEChanging(value);
                ReportPropertyChanging("MAIN_NAME");
                _MAIN_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MAIN_NAME");
                OnMAIN_NAMEChanged();
            }
        }
        private global::System.String _MAIN_NAME;
        partial void OnMAIN_NAMEChanging(global::System.String value);
        partial void OnMAIN_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MAIN_GROUP
        {
            get
            {
                return _MAIN_GROUP;
            }
            set
            {
                OnMAIN_GROUPChanging(value);
                ReportPropertyChanging("MAIN_GROUP");
                _MAIN_GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAIN_GROUP");
                OnMAIN_GROUPChanged();
            }
        }
        private Nullable<global::System.Decimal> _MAIN_GROUP;
        partial void OnMAIN_GROUPChanging(Nullable<global::System.Decimal> value);
        partial void OnMAIN_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CHANNEL_NAME
        {
            get
            {
                return _CHANNEL_NAME;
            }
            set
            {
                OnCHANNEL_NAMEChanging(value);
                ReportPropertyChanging("CHANNEL_NAME");
                _CHANNEL_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CHANNEL_NAME");
                OnCHANNEL_NAMEChanged();
            }
        }
        private global::System.String _CHANNEL_NAME;
        partial void OnCHANNEL_NAMEChanging(global::System.String value);
        partial void OnCHANNEL_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CHANNEL_GROUP
        {
            get
            {
                return _CHANNEL_GROUP;
            }
            set
            {
                OnCHANNEL_GROUPChanging(value);
                ReportPropertyChanging("CHANNEL_GROUP");
                _CHANNEL_GROUP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHANNEL_GROUP");
                OnCHANNEL_GROUPChanged();
            }
        }
        private Nullable<global::System.Decimal> _CHANNEL_GROUP;
        partial void OnCHANNEL_GROUPChanging(Nullable<global::System.Decimal> value);
        partial void OnCHANNEL_GROUPChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="v_WRK_MANAGEMENT_LETTERS_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_MANAGEMENT_LETTERS_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_MANAGEMENT_LETTERS_DATA object.
        /// </summary>
        /// <param name="pARENT_ID">Initial value of the PARENT_ID property.</param>
        public static v_WRK_MANAGEMENT_LETTERS_DATA Createv_WRK_MANAGEMENT_LETTERS_DATA(global::System.Decimal pARENT_ID)
        {
            v_WRK_MANAGEMENT_LETTERS_DATA v_WRK_MANAGEMENT_LETTERS_DATA = new v_WRK_MANAGEMENT_LETTERS_DATA();
            v_WRK_MANAGEMENT_LETTERS_DATA.PARENT_ID = pARENT_ID;
            return v_WRK_MANAGEMENT_LETTERS_DATA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PARENT_ID
        {
            get
            {
                return _PARENT_ID;
            }
            set
            {
                if (_PARENT_ID != value)
                {
                    OnPARENT_IDChanging(value);
                    ReportPropertyChanging("PARENT_ID");
                    _PARENT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PARENT_ID");
                    OnPARENT_IDChanged();
                }
            }
        }
        private global::System.Decimal _PARENT_ID;
        partial void OnPARENT_IDChanging(global::System.Decimal value);
        partial void OnPARENT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ORDER
        {
            get
            {
                return _ORDER;
            }
            set
            {
                OnORDERChanging(value);
                ReportPropertyChanging("ORDER");
                _ORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDER");
                OnORDERChanged();
            }
        }
        private Nullable<global::System.Decimal> _ORDER;
        partial void OnORDERChanging(Nullable<global::System.Decimal> value);
        partial void OnORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SHORT_NAME
        {
            get
            {
                return _SHORT_NAME;
            }
            set
            {
                OnSHORT_NAMEChanging(value);
                ReportPropertyChanging("SHORT_NAME");
                _SHORT_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SHORT_NAME");
                OnSHORT_NAMEChanged();
            }
        }
        private global::System.String _SHORT_NAME;
        partial void OnSHORT_NAMEChanging(global::System.String value);
        partial void OnSHORT_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _ID;
        partial void OnIDChanging(Nullable<global::System.Decimal> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_COL1
        {
            get
            {
                return _YTD_COL1;
            }
            set
            {
                OnYTD_COL1Changing(value);
                ReportPropertyChanging("YTD_COL1");
                _YTD_COL1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_COL1");
                OnYTD_COL1Changed();
            }
        }
        private Nullable<global::System.Decimal> _YTD_COL1;
        partial void OnYTD_COL1Changing(Nullable<global::System.Decimal> value);
        partial void OnYTD_COL1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_COL2
        {
            get
            {
                return _YTD_COL2;
            }
            set
            {
                OnYTD_COL2Changing(value);
                ReportPropertyChanging("YTD_COL2");
                _YTD_COL2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_COL2");
                OnYTD_COL2Changed();
            }
        }
        private Nullable<global::System.Decimal> _YTD_COL2;
        partial void OnYTD_COL2Changing(Nullable<global::System.Decimal> value);
        partial void OnYTD_COL2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YTD_COL3
        {
            get
            {
                return _YTD_COL3;
            }
            set
            {
                OnYTD_COL3Changing(value);
                ReportPropertyChanging("YTD_COL3");
                _YTD_COL3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_COL3");
                OnYTD_COL3Changed();
            }
        }
        private Nullable<global::System.Int32> _YTD_COL3;
        partial void OnYTD_COL3Changing(Nullable<global::System.Int32> value);
        partial void OnYTD_COL3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LATEST_COL1
        {
            get
            {
                return _LATEST_COL1;
            }
            set
            {
                OnLATEST_COL1Changing(value);
                ReportPropertyChanging("LATEST_COL1");
                _LATEST_COL1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATEST_COL1");
                OnLATEST_COL1Changed();
            }
        }
        private Nullable<global::System.Decimal> _LATEST_COL1;
        partial void OnLATEST_COL1Changing(Nullable<global::System.Decimal> value);
        partial void OnLATEST_COL1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LATEST_COL2
        {
            get
            {
                return _LATEST_COL2;
            }
            set
            {
                OnLATEST_COL2Changing(value);
                ReportPropertyChanging("LATEST_COL2");
                _LATEST_COL2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATEST_COL2");
                OnLATEST_COL2Changed();
            }
        }
        private Nullable<global::System.Decimal> _LATEST_COL2;
        partial void OnLATEST_COL2Changing(Nullable<global::System.Decimal> value);
        partial void OnLATEST_COL2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LATEST_COL3
        {
            get
            {
                return _LATEST_COL3;
            }
            set
            {
                OnLATEST_COL3Changing(value);
                ReportPropertyChanging("LATEST_COL3");
                _LATEST_COL3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LATEST_COL3");
                OnLATEST_COL3Changed();
            }
        }
        private Nullable<global::System.Int32> _LATEST_COL3;
        partial void OnLATEST_COL3Changing(Nullable<global::System.Int32> value);
        partial void OnLATEST_COL3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YEAR_PERIOD
        {
            get
            {
                return _YEAR_PERIOD;
            }
            set
            {
                OnYEAR_PERIODChanging(value);
                ReportPropertyChanging("YEAR_PERIOD");
                _YEAR_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YEAR_PERIOD");
                OnYEAR_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _YEAR_PERIOD;
        partial void OnYEAR_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnYEAR_PERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_PERIOD
        {
            get
            {
                return _MONTH_PERIOD;
            }
            set
            {
                OnMONTH_PERIODChanging(value);
                ReportPropertyChanging("MONTH_PERIOD");
                _MONTH_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_PERIOD");
                OnMONTH_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_PERIOD;
        partial void OnMONTH_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_PERIODChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="v_WRK_MONTHLY_COMMENTS_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_MONTHLY_COMMENTS_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_MONTHLY_COMMENTS_DATA object.
        /// </summary>
        /// <param name="cHANNEL">Initial value of the CHANNEL property.</param>
        /// <param name="oRDER">Initial value of the ORDER property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static v_WRK_MONTHLY_COMMENTS_DATA Createv_WRK_MONTHLY_COMMENTS_DATA(global::System.Decimal cHANNEL, global::System.Decimal oRDER, global::System.Int64 id)
        {
            v_WRK_MONTHLY_COMMENTS_DATA v_WRK_MONTHLY_COMMENTS_DATA = new v_WRK_MONTHLY_COMMENTS_DATA();
            v_WRK_MONTHLY_COMMENTS_DATA.CHANNEL = cHANNEL;
            v_WRK_MONTHLY_COMMENTS_DATA.ORDER = oRDER;
            v_WRK_MONTHLY_COMMENTS_DATA.ID = id;
            return v_WRK_MONTHLY_COMMENTS_DATA;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CHANNEL
        {
            get
            {
                return _CHANNEL;
            }
            set
            {
                OnCHANNELChanging(value);
                ReportPropertyChanging("CHANNEL");
                _CHANNEL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHANNEL");
                OnCHANNELChanged();
            }
        }
        private global::System.Decimal _CHANNEL;
        partial void OnCHANNELChanging(global::System.Decimal value);
        partial void OnCHANNELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_MARKET_GROWTH
        {
            get
            {
                return _MONTH_MARKET_GROWTH;
            }
            set
            {
                OnMONTH_MARKET_GROWTHChanging(value);
                ReportPropertyChanging("MONTH_MARKET_GROWTH");
                _MONTH_MARKET_GROWTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_MARKET_GROWTH");
                OnMONTH_MARKET_GROWTHChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_MARKET_GROWTH;
        partial void OnMONTH_MARKET_GROWTHChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_MARKET_GROWTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_BRAND_GROWTH
        {
            get
            {
                return _MONTH_BRAND_GROWTH;
            }
            set
            {
                OnMONTH_BRAND_GROWTHChanging(value);
                ReportPropertyChanging("MONTH_BRAND_GROWTH");
                _MONTH_BRAND_GROWTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_BRAND_GROWTH");
                OnMONTH_BRAND_GROWTHChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_BRAND_GROWTH;
        partial void OnMONTH_BRAND_GROWTHChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_BRAND_GROWTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_MARKET_SHARE
        {
            get
            {
                return _MONTH_MARKET_SHARE;
            }
            set
            {
                OnMONTH_MARKET_SHAREChanging(value);
                ReportPropertyChanging("MONTH_MARKET_SHARE");
                _MONTH_MARKET_SHARE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_MARKET_SHARE");
                OnMONTH_MARKET_SHAREChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_MARKET_SHARE;
        partial void OnMONTH_MARKET_SHAREChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_MARKET_SHAREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_PT
        {
            get
            {
                return _MONTH_PT;
            }
            set
            {
                OnMONTH_PTChanging(value);
                ReportPropertyChanging("MONTH_PT");
                _MONTH_PT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_PT");
                OnMONTH_PTChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_PT;
        partial void OnMONTH_PTChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_PTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_MARKET_GROWTH
        {
            get
            {
                return _YTD_MARKET_GROWTH;
            }
            set
            {
                OnYTD_MARKET_GROWTHChanging(value);
                ReportPropertyChanging("YTD_MARKET_GROWTH");
                _YTD_MARKET_GROWTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_MARKET_GROWTH");
                OnYTD_MARKET_GROWTHChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_MARKET_GROWTH;
        partial void OnYTD_MARKET_GROWTHChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_MARKET_GROWTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_BRAND_GROWTH
        {
            get
            {
                return _YTD_BRAND_GROWTH;
            }
            set
            {
                OnYTD_BRAND_GROWTHChanging(value);
                ReportPropertyChanging("YTD_BRAND_GROWTH");
                _YTD_BRAND_GROWTH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_BRAND_GROWTH");
                OnYTD_BRAND_GROWTHChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_BRAND_GROWTH;
        partial void OnYTD_BRAND_GROWTHChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_BRAND_GROWTHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_MARKET_SHARE
        {
            get
            {
                return _YTD_MARKET_SHARE;
            }
            set
            {
                OnYTD_MARKET_SHAREChanging(value);
                ReportPropertyChanging("YTD_MARKET_SHARE");
                _YTD_MARKET_SHARE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_MARKET_SHARE");
                OnYTD_MARKET_SHAREChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_MARKET_SHARE;
        partial void OnYTD_MARKET_SHAREChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_MARKET_SHAREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_PT
        {
            get
            {
                return _YTD_PT;
            }
            set
            {
                OnYTD_PTChanging(value);
                ReportPropertyChanging("YTD_PT");
                _YTD_PT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YTD_PT");
                OnYTD_PTChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_PT;
        partial void OnYTD_PTChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_PTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ORDER
        {
            get
            {
                return _ORDER;
            }
            set
            {
                OnORDERChanging(value);
                ReportPropertyChanging("ORDER");
                _ORDER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ORDER");
                OnORDERChanged();
            }
        }
        private global::System.Decimal _ORDER;
        partial void OnORDERChanging(global::System.Decimal value);
        partial void OnORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YEAR_PERIOD
        {
            get
            {
                return _YEAR_PERIOD;
            }
            set
            {
                OnYEAR_PERIODChanging(value);
                ReportPropertyChanging("YEAR_PERIOD");
                _YEAR_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YEAR_PERIOD");
                OnYEAR_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _YEAR_PERIOD;
        partial void OnYEAR_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnYEAR_PERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONTH_PERIOD
        {
            get
            {
                return _MONTH_PERIOD;
            }
            set
            {
                OnMONTH_PERIODChanging(value);
                ReportPropertyChanging("MONTH_PERIOD");
                _MONTH_PERIOD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONTH_PERIOD");
                OnMONTH_PERIODChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONTH_PERIOD;
        partial void OnMONTH_PERIODChanging(Nullable<global::System.Decimal> value);
        partial void OnMONTH_PERIODChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();

        #endregion

    
    }

    #endregion

    
}
