//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP_CONFIG
    {
        public decimal ID { get; set; }
        public Nullable<decimal> GROUP_ID { get; set; }
        public Nullable<decimal> BRAND { get; set; }
        public Nullable<decimal> MARKET { get; set; }
        public string BRAND_NAME { get; set; }
        public Nullable<decimal> CONFIG { get; set; }
        public Nullable<decimal> TYPE_ID { get; set; }
    }
}
