//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARKET_MASTER
    {
        public MARKET_MASTER()
        {
            this.BRAND_MASTER = new HashSet<BRAND_MASTER>();
            this.STRWM_BOY_DATA = new HashSet<STRWM_BOY_DATA>();
            this.STRWM_BRAND_DATA = new HashSet<STRWM_BRAND_DATA>();
            this.STRWM_MARKET_DATA = new HashSet<STRWM_MARKET_DATA>();
            this.STRWM_NTS_DATA = new HashSet<STRWM_NTS_DATA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> GROUP { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CHANNEL { get; set; }
        public Nullable<decimal> FRANCHISE { get; set; }
        public Nullable<decimal> KEYBRANDS { get; set; }
    
        public virtual ICollection<BRAND_MASTER> BRAND_MASTER { get; set; }
        public virtual ICollection<STRWM_BOY_DATA> STRWM_BOY_DATA { get; set; }
        public virtual ICollection<STRWM_BRAND_DATA> STRWM_BRAND_DATA { get; set; }
        public virtual ICollection<STRWM_MARKET_DATA> STRWM_MARKET_DATA { get; set; }
        public virtual ICollection<STRWM_NTS_DATA> STRWM_NTS_DATA { get; set; }
    }
}
