//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_CONFIG
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MENU_ID { get; set; }
        public string USER { get; set; }
        public string PERMISSION { get; set; }
    }
}
