//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERIOD_TABLE
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MONTH_PERIOD { get; set; }
        public Nullable<decimal> YEAR_PERIOD { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
