//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRWM_NTS_DATA
    {
        public decimal ID { get; set; }
        public decimal CHANNEL { get; set; }
        public decimal MARKET { get; set; }
        public decimal BRAND { get; set; }
        public decimal NTS_CFG { get; set; }
        public Nullable<decimal> MONTH_AMOUNT_ACTUAL { get; set; }
        public Nullable<decimal> MONTH_AMOUNT_FBP { get; set; }
        public Nullable<decimal> MONTH_AMOUNT_PY { get; set; }
        public Nullable<decimal> MONTH_CHANGE_FBP { get; set; }
        public Nullable<decimal> MONTH_CHANGE_PY { get; set; }
        public Nullable<decimal> YTD_AMOUNT_ACTUAL { get; set; }
        public Nullable<decimal> YTD_AMOUNT_FBP { get; set; }
        public Nullable<decimal> YTD_AMOUNT_PY { get; set; }
        public Nullable<decimal> YTD_CHANGE_FBP { get; set; }
        public Nullable<decimal> YTD_CHANGE_PY { get; set; }
        public Nullable<decimal> TRANSACTION_ID { get; set; }
        public Nullable<decimal> YEAR_PERIOD { get; set; }
        public Nullable<decimal> MONTH_PERIOD { get; set; }
        public string USER { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
    
        public virtual BRAND_MASTER BRAND_MASTER { get; set; }
        public virtual MARKET_MASTER MARKET_MASTER { get; set; }
    }
}
