//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRWM_MARKET_DATA
    {
        public decimal ID { get; set; }
        public string DATA { get; set; }
        public string SOURCE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> MARKET { get; set; }
        public Nullable<decimal> YEAR_PERIOD { get; set; }
        public Nullable<decimal> MONTH_PERIOD { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> MONTH { get; set; }
        public Nullable<decimal> YTD { get; set; }
        public Nullable<decimal> MAT { get; set; }
        public string WC { get; set; }
        public string SB { get; set; }
        public Nullable<decimal> TRANSACTION_ID { get; set; }
        public string USER { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
    
        public virtual MARKET_MASTER MARKET_MASTER { get; set; }
    }
}
