//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRWM_BMC_DATA
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> MKT_GP_ACT { get; set; }
        public Nullable<decimal> BME_ACT { get; set; }
        public Nullable<decimal> BMC_ACT { get; set; }
        public Nullable<decimal> MKT_GP_NTAR { get; set; }
        public Nullable<decimal> BME_NTAR { get; set; }
        public Nullable<decimal> BMC_NTAR { get; set; }
        public Nullable<decimal> MARKET { get; set; }
        public Nullable<decimal> BRAND { get; set; }
        public Nullable<decimal> CHANNEL { get; set; }
        public string CHANNEL_SHORT { get; set; }
        public Nullable<decimal> TRANSACTION_ID { get; set; }
        public string USER { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public Nullable<decimal> MONTH { get; set; }
        public string GFO { get; set; }
        public string PRIORITIZATION { get; set; }
    }
}
