//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRWM_BOY_DATA
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MARKET { get; set; }
        public Nullable<decimal> GROUP { get; set; }
        public string MARKET_NAME { get; set; }
        public string BRAND_NAME { get; set; }
        public string DATA { get; set; }
        public string SOURCE { get; set; }
        public Nullable<double> INT { get; set; }
        public Nullable<double> BTG { get; set; }
        public Nullable<double> PBP { get; set; }
        public Nullable<decimal> YEAR_PERIOD { get; set; }
        public Nullable<decimal> MONTH_PERIOD { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> CHANNEL { get; set; }
        public Nullable<decimal> BRAND { get; set; }
        public Nullable<decimal> TRANSACTION_ID { get; set; }
        public string USER { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
    
        public virtual BRAND_MASTER BRAND_MASTER { get; set; }
        public virtual MARKET_MASTER MARKET_MASTER { get; set; }
    }
}
