//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_MASTER
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string URL { get; set; }
        public string CONTROLLER { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> MENU_ID { get; set; }
        public string SELECT_DEFAULT { get; set; }
    }
}
