//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StrawmanApp.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class godzillaBrandCategorisationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new godzillaBrandCategorisationEntities object using the connection string found in the 'godzillaBrandCategorisationEntities' section of the application configuration file.
        /// </summary>
        public godzillaBrandCategorisationEntities() : base("name=godzillaBrandCategorisationEntities", "godzillaBrandCategorisationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new godzillaBrandCategorisationEntities object.
        /// </summary>
        public godzillaBrandCategorisationEntities(string connectionString) : base(connectionString, "godzillaBrandCategorisationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new godzillaBrandCategorisationEntities object.
        /// </summary>
        public godzillaBrandCategorisationEntities(EntityConnection connection) : base(connection, "godzillaBrandCategorisationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_BRAND_CATEGORISATION> v_WRK_BRAND_CATEGORISATION
        {
            get
            {
                if ((_v_WRK_BRAND_CATEGORISATION == null))
                {
                    _v_WRK_BRAND_CATEGORISATION = base.CreateObjectSet<v_WRK_BRAND_CATEGORISATION>("v_WRK_BRAND_CATEGORISATION");
                }
                return _v_WRK_BRAND_CATEGORISATION;
            }
        }
        private ObjectSet<v_WRK_BRAND_CATEGORISATION> _v_WRK_BRAND_CATEGORISATION;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_BRAND_CATEGORISATION_DATA> v_WRK_BRAND_CATEGORISATION_DATA
        {
            get
            {
                if ((_v_WRK_BRAND_CATEGORISATION_DATA == null))
                {
                    _v_WRK_BRAND_CATEGORISATION_DATA = base.CreateObjectSet<v_WRK_BRAND_CATEGORISATION_DATA>("v_WRK_BRAND_CATEGORISATION_DATA");
                }
                return _v_WRK_BRAND_CATEGORISATION_DATA;
            }
        }
        private ObjectSet<v_WRK_BRAND_CATEGORISATION_DATA> _v_WRK_BRAND_CATEGORISATION_DATA;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_WRK_BRAND_CATEGORISATION_MASTER> v_WRK_BRAND_CATEGORISATION_MASTER
        {
            get
            {
                if ((_v_WRK_BRAND_CATEGORISATION_MASTER == null))
                {
                    _v_WRK_BRAND_CATEGORISATION_MASTER = base.CreateObjectSet<v_WRK_BRAND_CATEGORISATION_MASTER>("v_WRK_BRAND_CATEGORISATION_MASTER");
                }
                return _v_WRK_BRAND_CATEGORISATION_MASTER;
            }
        }
        private ObjectSet<v_WRK_BRAND_CATEGORISATION_MASTER> _v_WRK_BRAND_CATEGORISATION_MASTER;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_BRAND_CATEGORISATION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_BRAND_CATEGORISATION(v_WRK_BRAND_CATEGORISATION v_WRK_BRAND_CATEGORISATION)
        {
            base.AddObject("v_WRK_BRAND_CATEGORISATION", v_WRK_BRAND_CATEGORISATION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_BRAND_CATEGORISATION_DATA EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_BRAND_CATEGORISATION_DATA(v_WRK_BRAND_CATEGORISATION_DATA v_WRK_BRAND_CATEGORISATION_DATA)
        {
            base.AddObject("v_WRK_BRAND_CATEGORISATION_DATA", v_WRK_BRAND_CATEGORISATION_DATA);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_WRK_BRAND_CATEGORISATION_MASTER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_WRK_BRAND_CATEGORISATION_MASTER(v_WRK_BRAND_CATEGORISATION_MASTER v_WRK_BRAND_CATEGORISATION_MASTER)
        {
            base.AddObject("v_WRK_BRAND_CATEGORISATION_MASTER", v_WRK_BRAND_CATEGORISATION_MASTER);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="godzillaBrandCategorisationModel", Name="v_WRK_BRAND_CATEGORISATION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_BRAND_CATEGORISATION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_BRAND_CATEGORISATION object.
        /// </summary>
        /// <param name="gROUP_LEVEL">Initial value of the GROUP_LEVEL property.</param>
        /// <param name="tYPE">Initial value of the TYPE property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static v_WRK_BRAND_CATEGORISATION Createv_WRK_BRAND_CATEGORISATION(global::System.Decimal gROUP_LEVEL, global::System.Decimal tYPE, global::System.Decimal id)
        {
            v_WRK_BRAND_CATEGORISATION v_WRK_BRAND_CATEGORISATION = new v_WRK_BRAND_CATEGORISATION();
            v_WRK_BRAND_CATEGORISATION.GROUP_LEVEL = gROUP_LEVEL;
            v_WRK_BRAND_CATEGORISATION.TYPE = tYPE;
            v_WRK_BRAND_CATEGORISATION.ID = id;
            return v_WRK_BRAND_CATEGORISATION;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUP_LEVEL
        {
            get
            {
                return _GROUP_LEVEL;
            }
            set
            {
                if (_GROUP_LEVEL != value)
                {
                    OnGROUP_LEVELChanging(value);
                    ReportPropertyChanging("GROUP_LEVEL");
                    _GROUP_LEVEL = StructuralObject.SetValidValue(value, "GROUP_LEVEL");
                    ReportPropertyChanged("GROUP_LEVEL");
                    OnGROUP_LEVELChanged();
                }
            }
        }
        private global::System.Decimal _GROUP_LEVEL;
        partial void OnGROUP_LEVELChanging(global::System.Decimal value);
        partial void OnGROUP_LEVELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUP_NAME
        {
            get
            {
                return _GROUP_NAME;
            }
            set
            {
                OnGROUP_NAMEChanging(value);
                ReportPropertyChanging("GROUP_NAME");
                _GROUP_NAME = StructuralObject.SetValidValue(value, true, "GROUP_NAME");
                ReportPropertyChanged("GROUP_NAME");
                OnGROUP_NAMEChanged();
            }
        }
        private global::System.String _GROUP_NAME;
        partial void OnGROUP_NAMEChanging(global::System.String value);
        partial void OnGROUP_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ORDER
        {
            get
            {
                return _ORDER;
            }
            set
            {
                OnORDERChanging(value);
                ReportPropertyChanging("ORDER");
                _ORDER = StructuralObject.SetValidValue(value, "ORDER");
                ReportPropertyChanged("ORDER");
                OnORDERChanged();
            }
        }
        private Nullable<global::System.Decimal> _ORDER;
        partial void OnORDERChanging(Nullable<global::System.Decimal> value);
        partial void OnORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    OnTYPEChanging(value);
                    ReportPropertyChanging("TYPE");
                    _TYPE = StructuralObject.SetValidValue(value, "TYPE");
                    ReportPropertyChanged("TYPE");
                    OnTYPEChanged();
                }
            }
        }
        private global::System.Decimal _TYPE;
        partial void OnTYPEChanging(global::System.Decimal value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BRAND
        {
            get
            {
                return _BRAND;
            }
            set
            {
                OnBRANDChanging(value);
                ReportPropertyChanging("BRAND");
                _BRAND = StructuralObject.SetValidValue(value, "BRAND");
                ReportPropertyChanged("BRAND");
                OnBRANDChanged();
            }
        }
        private Nullable<global::System.Decimal> _BRAND;
        partial void OnBRANDChanging(Nullable<global::System.Decimal> value);
        partial void OnBRANDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MARKET
        {
            get
            {
                return _MARKET;
            }
            set
            {
                OnMARKETChanging(value);
                ReportPropertyChanging("MARKET");
                _MARKET = StructuralObject.SetValidValue(value, "MARKET");
                ReportPropertyChanged("MARKET");
                OnMARKETChanged();
            }
        }
        private Nullable<global::System.Decimal> _MARKET;
        partial void OnMARKETChanging(Nullable<global::System.Decimal> value);
        partial void OnMARKETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BRAND_NAME
        {
            get
            {
                return _BRAND_NAME;
            }
            set
            {
                OnBRAND_NAMEChanging(value);
                ReportPropertyChanging("BRAND_NAME");
                _BRAND_NAME = StructuralObject.SetValidValue(value, true, "BRAND_NAME");
                ReportPropertyChanged("BRAND_NAME");
                OnBRAND_NAMEChanged();
            }
        }
        private global::System.String _BRAND_NAME;
        partial void OnBRAND_NAMEChanging(global::System.String value);
        partial void OnBRAND_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CONFIG
        {
            get
            {
                return _CONFIG;
            }
            set
            {
                OnCONFIGChanging(value);
                ReportPropertyChanging("CONFIG");
                _CONFIG = StructuralObject.SetValidValue(value, "CONFIG");
                ReportPropertyChanged("CONFIG");
                OnCONFIGChanged();
            }
        }
        private Nullable<global::System.Decimal> _CONFIG;
        partial void OnCONFIGChanging(Nullable<global::System.Decimal> value);
        partial void OnCONFIGChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="godzillaBrandCategorisationModel", Name="v_WRK_BRAND_CATEGORISATION_DATA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_BRAND_CATEGORISATION_DATA : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_BRAND_CATEGORISATION_DATA object.
        /// </summary>
        /// <param name="gROUP_LEVEL">Initial value of the GROUP_LEVEL property.</param>
        /// <param name="tYPE">Initial value of the TYPE property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static v_WRK_BRAND_CATEGORISATION_DATA Createv_WRK_BRAND_CATEGORISATION_DATA(global::System.Decimal gROUP_LEVEL, global::System.Decimal tYPE, global::System.Decimal id)
        {
            v_WRK_BRAND_CATEGORISATION_DATA v_WRK_BRAND_CATEGORISATION_DATA = new v_WRK_BRAND_CATEGORISATION_DATA();
            v_WRK_BRAND_CATEGORISATION_DATA.GROUP_LEVEL = gROUP_LEVEL;
            v_WRK_BRAND_CATEGORISATION_DATA.TYPE = tYPE;
            v_WRK_BRAND_CATEGORISATION_DATA.ID = id;
            return v_WRK_BRAND_CATEGORISATION_DATA;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUP_LEVEL
        {
            get
            {
                return _GROUP_LEVEL;
            }
            set
            {
                if (_GROUP_LEVEL != value)
                {
                    OnGROUP_LEVELChanging(value);
                    ReportPropertyChanging("GROUP_LEVEL");
                    _GROUP_LEVEL = StructuralObject.SetValidValue(value, "GROUP_LEVEL");
                    ReportPropertyChanged("GROUP_LEVEL");
                    OnGROUP_LEVELChanged();
                }
            }
        }
        private global::System.Decimal _GROUP_LEVEL;
        partial void OnGROUP_LEVELChanging(global::System.Decimal value);
        partial void OnGROUP_LEVELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ORDER
        {
            get
            {
                return _ORDER;
            }
            set
            {
                OnORDERChanging(value);
                ReportPropertyChanging("ORDER");
                _ORDER = StructuralObject.SetValidValue(value, "ORDER");
                ReportPropertyChanged("ORDER");
                OnORDERChanged();
            }
        }
        private Nullable<global::System.Decimal> _ORDER;
        partial void OnORDERChanging(Nullable<global::System.Decimal> value);
        partial void OnORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUP_NAME
        {
            get
            {
                return _GROUP_NAME;
            }
            set
            {
                OnGROUP_NAMEChanging(value);
                ReportPropertyChanging("GROUP_NAME");
                _GROUP_NAME = StructuralObject.SetValidValue(value, true, "GROUP_NAME");
                ReportPropertyChanged("GROUP_NAME");
                OnGROUP_NAMEChanged();
            }
        }
        private global::System.String _GROUP_NAME;
        partial void OnGROUP_NAMEChanging(global::System.String value);
        partial void OnGROUP_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    OnTYPEChanging(value);
                    ReportPropertyChanging("TYPE");
                    _TYPE = StructuralObject.SetValidValue(value, "TYPE");
                    ReportPropertyChanged("TYPE");
                    OnTYPEChanged();
                }
            }
        }
        private global::System.Decimal _TYPE;
        partial void OnTYPEChanging(global::System.Decimal value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ACT
        {
            get
            {
                return _ACT;
            }
            set
            {
                OnACTChanging(value);
                ReportPropertyChanging("ACT");
                _ACT = StructuralObject.SetValidValue(value, "ACT");
                ReportPropertyChanged("ACT");
                OnACTChanged();
            }
        }
        private Nullable<global::System.Decimal> _ACT;
        partial void OnACTChanging(Nullable<global::System.Decimal> value);
        partial void OnACTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PY
        {
            get
            {
                return _PY;
            }
            set
            {
                OnPYChanging(value);
                ReportPropertyChanging("PY");
                _PY = StructuralObject.SetValidValue(value, "PY");
                ReportPropertyChanged("PY");
                OnPYChanged();
            }
        }
        private Nullable<global::System.Decimal> _PY;
        partial void OnPYChanging(Nullable<global::System.Decimal> value);
        partial void OnPYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_SHARE_VS_PY
        {
            get
            {
                return _YTD_SHARE_VS_PY;
            }
            set
            {
                OnYTD_SHARE_VS_PYChanging(value);
                ReportPropertyChanging("YTD_SHARE_VS_PY");
                _YTD_SHARE_VS_PY = StructuralObject.SetValidValue(value, "YTD_SHARE_VS_PY");
                ReportPropertyChanged("YTD_SHARE_VS_PY");
                OnYTD_SHARE_VS_PYChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_SHARE_VS_PY;
        partial void OnYTD_SHARE_VS_PYChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_SHARE_VS_PYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> YTD_CATEGORY_VS_PY
        {
            get
            {
                return _YTD_CATEGORY_VS_PY;
            }
            set
            {
                OnYTD_CATEGORY_VS_PYChanging(value);
                ReportPropertyChanging("YTD_CATEGORY_VS_PY");
                _YTD_CATEGORY_VS_PY = StructuralObject.SetValidValue(value, "YTD_CATEGORY_VS_PY");
                ReportPropertyChanged("YTD_CATEGORY_VS_PY");
                OnYTD_CATEGORY_VS_PYChanged();
            }
        }
        private Nullable<global::System.Decimal> _YTD_CATEGORY_VS_PY;
        partial void OnYTD_CATEGORY_VS_PYChanging(Nullable<global::System.Decimal> value);
        partial void OnYTD_CATEGORY_VS_PYChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="godzillaBrandCategorisationModel", Name="v_WRK_BRAND_CATEGORISATION_MASTER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_WRK_BRAND_CATEGORISATION_MASTER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_WRK_BRAND_CATEGORISATION_MASTER object.
        /// </summary>
        /// <param name="gROUP_LEVEL">Initial value of the GROUP_LEVEL property.</param>
        /// <param name="tYPE">Initial value of the TYPE property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static v_WRK_BRAND_CATEGORISATION_MASTER Createv_WRK_BRAND_CATEGORISATION_MASTER(global::System.Decimal gROUP_LEVEL, global::System.Decimal tYPE, global::System.Decimal id)
        {
            v_WRK_BRAND_CATEGORISATION_MASTER v_WRK_BRAND_CATEGORISATION_MASTER = new v_WRK_BRAND_CATEGORISATION_MASTER();
            v_WRK_BRAND_CATEGORISATION_MASTER.GROUP_LEVEL = gROUP_LEVEL;
            v_WRK_BRAND_CATEGORISATION_MASTER.TYPE = tYPE;
            v_WRK_BRAND_CATEGORISATION_MASTER.ID = id;
            return v_WRK_BRAND_CATEGORISATION_MASTER;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal GROUP_LEVEL
        {
            get
            {
                return _GROUP_LEVEL;
            }
            set
            {
                if (_GROUP_LEVEL != value)
                {
                    OnGROUP_LEVELChanging(value);
                    ReportPropertyChanging("GROUP_LEVEL");
                    _GROUP_LEVEL = StructuralObject.SetValidValue(value, "GROUP_LEVEL");
                    ReportPropertyChanged("GROUP_LEVEL");
                    OnGROUP_LEVELChanged();
                }
            }
        }
        private global::System.Decimal _GROUP_LEVEL;
        partial void OnGROUP_LEVELChanging(global::System.Decimal value);
        partial void OnGROUP_LEVELChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GROUP_NAME
        {
            get
            {
                return _GROUP_NAME;
            }
            set
            {
                OnGROUP_NAMEChanging(value);
                ReportPropertyChanging("GROUP_NAME");
                _GROUP_NAME = StructuralObject.SetValidValue(value, true, "GROUP_NAME");
                ReportPropertyChanged("GROUP_NAME");
                OnGROUP_NAMEChanged();
            }
        }
        private global::System.String _GROUP_NAME;
        partial void OnGROUP_NAMEChanging(global::System.String value);
        partial void OnGROUP_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ORDER
        {
            get
            {
                return _ORDER;
            }
            set
            {
                OnORDERChanging(value);
                ReportPropertyChanging("ORDER");
                _ORDER = StructuralObject.SetValidValue(value, "ORDER");
                ReportPropertyChanged("ORDER");
                OnORDERChanged();
            }
        }
        private Nullable<global::System.Decimal> _ORDER;
        partial void OnORDERChanging(Nullable<global::System.Decimal> value);
        partial void OnORDERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true, "NAME");
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TYPE
        {
            get
            {
                return _TYPE;
            }
            set
            {
                if (_TYPE != value)
                {
                    OnTYPEChanging(value);
                    ReportPropertyChanging("TYPE");
                    _TYPE = StructuralObject.SetValidValue(value, "TYPE");
                    ReportPropertyChanged("TYPE");
                    OnTYPEChanged();
                }
            }
        }
        private global::System.Decimal _TYPE;
        partial void OnTYPEChanging(global::System.Decimal value);
        partial void OnTYPEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();

        #endregion

    }

    #endregion

}
