<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="BOYDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=S18005030\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_WRK_BOY_BASE" Member="v_WRK_BOY_BASE">
    <Type Name="v_WRK_BOY_BASE">
      <Column Name="TYPE" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(261)" CanBeNull="true" />
      <Column Name="[BRAND COL1]" Member="BRAND_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BRAND COL2]" Member="BRAND_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[NTS COL1]" Member="NTS_COL1" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="[NTS COL2]" Member="NTS_COL2" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="[SUM ROWS]" Member="SUM_ROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_DATA_PBP" Member="v_WRK_BOY_CUSTOM_DATA_PBP">
    <Type Name="v_WRK_BOY_CUSTOM_DATA_PBP">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_BASIC_DATA" Member="v_WRK_BOY_BASIC_DATA">
    <Type Name="v_WRK_BOY_BASIC_DATA">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(261)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET CO1]" Member="MARKET_CO1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE PC]" Member="SHARE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Decimal" DbType="Decimal(23,0)" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE1]" Member="CONVERSION_RATE1" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE2]" Member="CONVERSION_RATE2" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CALC_DATA" Member="v_WRK_BOY_CALC_DATA">
    <Type Name="v_WRK_BOY_CALC_DATA">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CALC_DATA_INT" Member="v_WRK_BOY_CALC_DATA_INT">
    <Type Name="v_WRK_BOY_CALC_DATA_INT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(267)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[SUM ROWS]" Member="SUM_ROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CALC_DATA_LE" Member="v_WRK_BOY_CALC_DATA_LE">
    <Type Name="v_WRK_BOY_CALC_DATA_LE">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(267)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PC INT]" Member="SELLIN_PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[SUM ROWS]" Member="SUM_ROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CALC_DATA_PBP" Member="v_WRK_BOY_CALC_DATA_PBP">
    <Type Name="v_WRK_BOY_CALC_DATA_PBP">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(267)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[SUM ROWS]" Member="SUM_ROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE" Member="v_WRK_BOY_CUSTOM_BASE">
    <Type Name="v_WRK_BOY_CUSTOM_BASE">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET PBP]" Member="MARKET_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PBP PC]" Member="MARKET_PBP_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET 2 PBP]" Member="MARKET_2_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET 2 PBP ID]" Member="MARKET_2_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND PBP]" Member="BRAND_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[BRAND PBP PC]" Member="BRAND_PBP_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT 2 PBP]" Member="SELLOUT_2_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT 2 PBP ID]" Member="SELLOUT_2_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN LE]" Member="SELLIN_LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN 2 PBP]" Member="SELLIN_2_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN 2 PBP ID]" Member="SELLIN_2_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET 2 TYPE]" Member="MARKET_2_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT 2 TYPE]" Member="SELLOUT_2_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN 2 TYPE]" Member="SELLIN_2_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET INT]" Member="MARKET_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET INT PC]" Member="MARKET_INT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET 1 INT]" Member="MARKET_1_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET 1 INT ID]" Member="MARKET_1_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND INT]" Member="BRAND_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[BRAND INT PC]" Member="BRAND_INT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT 1 INT]" Member="SELLOUT_1_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT 1 INT ID]" Member="SELLOUT_1_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[TOTALS SHARE COL1]" Member="TOTALS_SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[TOTALS SHARE COL2]" Member="TOTALS_SHARE_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN TOTALS]" Member="SELLIN_TOTALS" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="[SELLIN 1 INT]" Member="SELLIN_1_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN 1 INT ID]" Member="SELLIN_1_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET 1 TYPE]" Member="MARKET_1_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT 1 TYPE]" Member="SELLOUT_1_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN 1 TYPE]" Member="SELLIN_1_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET TOGO]" Member="MARKET_TOGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET LE]" Member="MARKET_LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET LE PC]" Member="MARKET_LE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET 1 BTG]" Member="MARKET_1_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET 1 BTG ID]" Member="MARKET_1_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLOUT TOGO]" Member="SELLOUT_TOGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BRAND LE]" Member="BRAND_LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[BRAND LE PC]" Member="BRAND_LE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT 1 BTG]" Member="SELLOUT_1_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT 1 BTG ID]" Member="SELLOUT_1_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN TOGO]" Member="SELLIN_TOGO" Type="System.Decimal" DbType="Decimal(23,0)" CanBeNull="true" />
      <Column Name="[SELLIN YTD]" Member="SELLIN_YTD" Type="System.Decimal" DbType="Decimal(22,0)" CanBeNull="true" />
      <Column Name="[SELLIN 1 BTG]" Member="SELLIN_1_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN 1 BTG ID]" Member="SELLIN_1_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_TOTAL" Member="v_WRK_BOY_CUSTOM_BASE_TOTAL">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_TOTAL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_TOTAL_INT" Member="v_WRK_BOY_CUSTOM_BASE_TOTAL_INT">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_TOTAL_INT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_TOTAL_LE" Member="v_WRK_BOY_CUSTOM_BASE_TOTAL_LE">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_TOTAL_LE">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_TOTAL_PBP" Member="v_WRK_BOY_CUSTOM_BASE_TOTAL_PBP">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_TOTAL_PBP">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_DATA" Member="v_WRK_BOY_CUSTOM_DATA">
    <Type Name="v_WRK_BOY_CUSTOM_DATA">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_DATA_INT" Member="v_WRK_BOY_CUSTOM_DATA_INT">
    <Type Name="v_WRK_BOY_CUSTOM_DATA_INT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN  PC INT]" Member="SELLIN__PC_INT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_DATA_LE" Member="v_WRK_BOY_CUSTOM_DATA_LE">
    <Type Name="v_WRK_BOY_CUSTOM_DATA_LE">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET BOY]" Member="MARKET_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BOY]" Member="SELLOUT_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN BOY]" Member="SELLIN_BOY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_INT" Member="v_WRK_BOY_CUSTOM_BASE_INT">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_INT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET INT]" Member="MARKET_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET INT PC]" Member="MARKET_INT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET 1 INT]" Member="MARKET_1_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET 1 INT ID]" Member="MARKET_1_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND INT]" Member="BRAND_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[BRAND INT PC]" Member="BRAND_INT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT INT]" Member="SELLOUT_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT INT ID]" Member="SELLOUT_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[TOTALS SHARE COL1]" Member="TOTALS_SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[TOTALS SHARE COL2]" Member="TOTALS_SHARE_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN TOTALS]" Member="SELLIN_TOTALS" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN INT]" Member="SELLIN_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN INT ID]" Member="SELLIN_INT_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_PBP" Member="v_WRK_BOY_CUSTOM_BASE_PBP">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_PBP">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET PBP PC]" Member="MARKET_PBP_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET 2 PBP]" Member="MARKET_2_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PBP ID]" Member="MARKET_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[BRAND PBP]" Member="BRAND_PBP" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BRAND PBP PC]" Member="BRAND_PBP_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PBP]" Member="SELLOUT_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PBP ID]" Member="SELLOUT_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN LE]" Member="SELLIN_LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PBP]" Member="SELLIN_PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PBP ID]" Member="SELLIN_PBP_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BOY_CUSTOM_BASE_LE" Member="v_WRK_BOY_CUSTOM_BASE_LE">
    <Type Name="v_WRK_BOY_CUSTOM_BASE_LE">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MARKET NAME]" Member="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[MARKET TOGO]" Member="MARKET_TOGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET LE]" Member="MARKET_LE" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET LE PC]" Member="MARKET_LE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[MARKET BTG]" Member="MARKET_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET BTG ID]" Member="MARKET_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLOUT TOGO]" Member="SELLOUT_TOGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BRAND LE]" Member="BRAND_LE" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BRAND LE PC]" Member="BRAND_LE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT BTG]" Member="SELLOUT_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT BTG ID]" Member="SELLOUT_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[SELLIN TOGO]" Member="SELLIN_TOGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN YTD]" Member="SELLIN_YTD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN BTG]" Member="SELLIN_BTG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN BTG ID]" Member="SELLIN_BTG_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>