<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="ChannelsDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VM22078D0\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_WRK_BRAND_BY_CHANNEL" Member="v_WRK_BRAND_BY_CHANNEL">
    <Type Name="v_WRK_BRAND_BY_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL1]" Member="TOTAL_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL2]" Member="TOTAL_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_CHANNEL_DATA" Member="v_WRK_CHANNEL_DATA">
    <Type Name="v_WRK_CHANNEL_DATA">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(261)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_PCVSPY_CHANNEL" Member="v_WRK_MARKET_PCVSPY_CHANNEL">
    <Type Name="v_WRK_MARKET_PCVSPY_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL" Member="v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL">
    <Type Name="v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_BTG_CHANNEL" Member="v_WRK_BRAND_BTG_CHANNEL">
    <Type Name="v_WRK_BRAND_BTG_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_MAT_CHANNEL" Member="v_WRK_BRAND_MAT_CHANNEL">
    <Type Name="v_WRK_BRAND_MAT_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_PCVSPY_CHANNEL" Member="v_WRK_BRAND_PCVSPY_CHANNEL">
    <Type Name="v_WRK_BRAND_PCVSPY_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_BOY_CHANNEL" Member="v_WRK_BRAND_BOY_CHANNEL">
    <Type Name="v_WRK_BRAND_BOY_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL" Member="v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL">
    <Type Name="v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_YTD_CHANNEL" Member="v_WRK_BRAND_YTD_CHANNEL">
    <Type Name="v_WRK_BRAND_YTD_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_MONTH_CHANNEL" Member="v_WRK_BRAND_MONTH_CHANNEL">
    <Type Name="v_WRK_BRAND_MONTH_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_BOY_CHANNEL" Member="v_WRK_MARKET_BOY_CHANNEL">
    <Type Name="v_WRK_MARKET_BOY_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_BTG_CHANNEL" Member="v_WRK_MARKET_BTG_CHANNEL">
    <Type Name="v_WRK_MARKET_BTG_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[BTG COL1]" Member="BTG_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BTG COL2]" Member="BTG_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_MAT_CHANNEL" Member="v_WRK_MARKET_MAT_CHANNEL">
    <Type Name="v_WRK_MARKET_MAT_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_MONTH_CHANNEL" Member="v_WRK_MARKET_MONTH_CHANNEL">
    <Type Name="v_WRK_MARKET_MONTH_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_YTD_CHANNEL" Member="v_WRK_MARKET_YTD_CHANNEL">
    <Type Name="v_WRK_MARKET_YTD_CHANNEL">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHANNEL_MASTER" Member="CHANNEL_MASTER">
    <Type Name="CHANNEL_MASTER">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>