#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class ChannelsDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHANNEL_MASTER(CHANNEL_MASTER instance);
    partial void UpdateCHANNEL_MASTER(CHANNEL_MASTER instance);
    partial void DeleteCHANNEL_MASTER(CHANNEL_MASTER instance);
    #endregion
		
		public ChannelsDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChannelsDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChannelsDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChannelsDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChannelsDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BY_CHANNEL> v_WRK_BRAND_BY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_CHANNEL_DATA> v_WRK_CHANNEL_DATA
		{
			get
			{
				return this.GetTable<v_WRK_CHANNEL_DATA>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_PCVSPY_CHANNEL> v_WRK_MARKET_PCVSPY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_PCVSPY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL> v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BTG_CHANNEL> v_WRK_BRAND_BTG_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BTG_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MAT_CHANNEL> v_WRK_BRAND_MAT_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MAT_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_PCVSPY_CHANNEL> v_WRK_BRAND_PCVSPY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_PCVSPY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BOY_CHANNEL> v_WRK_BRAND_BOY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BOY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL> v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_YTD_CHANNEL> v_WRK_BRAND_YTD_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_YTD_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MONTH_CHANNEL> v_WRK_BRAND_MONTH_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MONTH_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BOY_CHANNEL> v_WRK_MARKET_BOY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BOY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BTG_CHANNEL> v_WRK_MARKET_BTG_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BTG_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MAT_CHANNEL> v_WRK_MARKET_MAT_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MAT_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MONTH_CHANNEL> v_WRK_MARKET_MONTH_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MONTH_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_YTD_CHANNEL> v_WRK_MARKET_YTD_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_YTD_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<CHANNEL_MASTER> CHANNEL_MASTER
		{
			get
			{
				return this.GetTable<CHANNEL_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BY_CHANNEL")]
	public partial class v_WRK_BRAND_BY_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _YTD_COL1;
		
		private System.Nullable<decimal> _YTD_COL2;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _TOTAL_COL1;
		
		private System.Nullable<decimal> _TOTAL_COL2;
		
		private System.Nullable<decimal> _MONTH_COL1;
		
		private System.Nullable<decimal> _MONTH_COL2;
		
		public v_WRK_BRAND_BY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL1]", Storage="_YTD_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL1
		{
			get
			{
				return this._YTD_COL1;
			}
			set
			{
				if ((this._YTD_COL1 != value))
				{
					this._YTD_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL2]", Storage="_YTD_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL2
		{
			get
			{
				return this._YTD_COL2;
			}
			set
			{
				if ((this._YTD_COL2 != value))
				{
					this._YTD_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL COL1]", Storage="_TOTAL_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL_COL1
		{
			get
			{
				return this._TOTAL_COL1;
			}
			set
			{
				if ((this._TOTAL_COL1 != value))
				{
					this._TOTAL_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL COL2]", Storage="_TOTAL_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL_COL2
		{
			get
			{
				return this._TOTAL_COL2;
			}
			set
			{
				if ((this._TOTAL_COL2 != value))
				{
					this._TOTAL_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL1]", Storage="_MONTH_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL1
		{
			get
			{
				return this._MONTH_COL1;
			}
			set
			{
				if ((this._MONTH_COL1 != value))
				{
					this._MONTH_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL2]", Storage="_MONTH_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL2
		{
			get
			{
				return this._MONTH_COL2;
			}
			set
			{
				if ((this._MONTH_COL2 != value))
				{
					this._MONTH_COL2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_CHANNEL_DATA")]
	public partial class v_WRK_CHANNEL_DATA
	{
		
		private decimal _ID;
		
		private string _NAME;
		
		public v_WRK_CHANNEL_DATA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(261)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_PCVSPY_CHANNEL")]
	public partial class v_WRK_MARKET_PCVSPY_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_PCVSPY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL")]
	public partial class v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_TOTAL_CUSTOM_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BTG_CHANNEL")]
	public partial class v_WRK_BRAND_BTG_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BTG_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MAT_CHANNEL")]
	public partial class v_WRK_BRAND_MAT_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MAT_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_PCVSPY_CHANNEL")]
	public partial class v_WRK_BRAND_PCVSPY_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_PCVSPY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BOY_CHANNEL")]
	public partial class v_WRK_BRAND_BOY_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BOY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL")]
	public partial class v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_TOTAL_CUSTOM_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_YTD_CHANNEL")]
	public partial class v_WRK_BRAND_YTD_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _YTD_COL1;
		
		private System.Nullable<decimal> _YTD_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_YTD_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL1]", Storage="_YTD_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL1
		{
			get
			{
				return this._YTD_COL1;
			}
			set
			{
				if ((this._YTD_COL1 != value))
				{
					this._YTD_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL2]", Storage="_YTD_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL2
		{
			get
			{
				return this._YTD_COL2;
			}
			set
			{
				if ((this._YTD_COL2 != value))
				{
					this._YTD_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MONTH_CHANNEL")]
	public partial class v_WRK_BRAND_MONTH_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _MONTH_COL1;
		
		private System.Nullable<decimal> _MONTH_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MONTH_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL1]", Storage="_MONTH_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL1
		{
			get
			{
				return this._MONTH_COL1;
			}
			set
			{
				if ((this._MONTH_COL1 != value))
				{
					this._MONTH_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL2]", Storage="_MONTH_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL2
		{
			get
			{
				return this._MONTH_COL2;
			}
			set
			{
				if ((this._MONTH_COL2 != value))
				{
					this._MONTH_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BOY_CHANNEL")]
	public partial class v_WRK_MARKET_BOY_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_BOY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BTG_CHANNEL")]
	public partial class v_WRK_MARKET_BTG_CHANNEL
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _BTG_COL1;
		
		private System.Nullable<double> _BTG_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_BTG_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BTG COL1]", Storage="_BTG_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> BTG_COL1
		{
			get
			{
				return this._BTG_COL1;
			}
			set
			{
				if ((this._BTG_COL1 != value))
				{
					this._BTG_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BTG COL2]", Storage="_BTG_COL2", DbType="Float")]
		public System.Nullable<double> BTG_COL2
		{
			get
			{
				return this._BTG_COL2;
			}
			set
			{
				if ((this._BTG_COL2 != value))
				{
					this._BTG_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MAT_CHANNEL")]
	public partial class v_WRK_MARKET_MAT_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MAT_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MONTH_CHANNEL")]
	public partial class v_WRK_MARKET_MONTH_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MONTH_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_YTD_CHANNEL")]
	public partial class v_WRK_MARKET_YTD_CHANNEL
	{
		
		private decimal _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private int _MARKET;
		
		private int _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_YTD_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0) NOT NULL")]
		public decimal CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Int NOT NULL")]
		public int MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Int NOT NULL")]
		public int BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHANNEL_MASTER")]
	public partial class CHANNEL_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private string _NAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    #endregion
		
		public CHANNEL_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
