#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class ChartsClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ChartsClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChartsClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChartsClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChartsClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChartsClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_CHART_BTG_ADULTS_SKINCARE> v_CHART_BTG_ADULTS_SKINCARE
		{
			get
			{
				return this.GetTable<v_CHART_BTG_ADULTS_SKINCARE>();
			}
		}
		
		public System.Data.Linq.Table<v_CHART_BTG_FRANCHISE> v_CHART_BTG_FRANCHISE
		{
			get
			{
				return this.GetTable<v_CHART_BTG_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_CHARTS_BTG> v_CHARTS_BTG
		{
			get
			{
				return this.GetTable<v_CHARTS_BTG>();
			}
		}
		
		public System.Data.Linq.Table<v_CHART_PBP_ADULTS_SKINCARE> v_CHART_PBP_ADULTS_SKINCARE
		{
			get
			{
				return this.GetTable<v_CHART_PBP_ADULTS_SKINCARE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_CHART_BY_CHANNEL> v_WRK_CHART_BY_CHANNEL
		{
			get
			{
				return this.GetTable<v_WRK_CHART_BY_CHANNEL>();
			}
		}
		
		public System.Data.Linq.Table<v_CHARTS_YTD> v_CHARTS_YTD
		{
			get
			{
				return this.GetTable<v_CHARTS_YTD>();
			}
		}
		
		public System.Data.Linq.Table<v_CHARTS_LM> v_CHARTS_LM
		{
			get
			{
				return this.GetTable<v_CHARTS_LM>();
			}
		}
		
		public System.Data.Linq.Table<v_CHART_PBP_FRANCHISE> v_CHART_PBP_FRANCHISE
		{
			get
			{
				return this.GetTable<v_CHART_PBP_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_CHARTS_PBP> v_CHARTS_PBP
		{
			get
			{
				return this.GetTable<v_CHARTS_PBP>();
			}
		}
		
		public System.Data.Linq.Table<v_CHARTS_MAT_MARKET> v_CHARTS_MAT_MARKET
		{
			get
			{
				return this.GetTable<v_CHARTS_MAT_MARKET>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHART_BTG_ADULTS_SKINCARE")]
	public partial class v_CHART_BTG_ADULTS_SKINCARE
	{
		
		private decimal _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private decimal _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<double> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		public v_CHART_BTG_ADULTS_SKINCARE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0) NOT NULL")]
		public decimal GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Float")]
		public System.Nullable<double> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHART_BTG_FRANCHISE")]
	public partial class v_CHART_BTG_FRANCHISE
	{
		
		private decimal _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private decimal _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<double> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		public v_CHART_BTG_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0) NOT NULL")]
		public decimal GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Float")]
		public System.Nullable<double> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHARTS_BTG")]
	public partial class v_CHARTS_BTG
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private decimal _MARKET;
		
		private decimal _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<double> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		public v_CHARTS_BTG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(18,0) NOT NULL")]
		public decimal MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(4000)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Float")]
		public System.Nullable<double> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHART_PBP_ADULTS_SKINCARE")]
	public partial class v_CHART_PBP_ADULTS_SKINCARE
	{
		
		private decimal _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private decimal _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHART_PBP_ADULTS_SKINCARE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0) NOT NULL")]
		public decimal GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_CATEGORY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_J_J", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_CHART_BY_CHANNEL")]
	public partial class v_WRK_CHART_BY_CHANNEL
	{
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _MAT_MARKET_SIZE;
		
		private System.Nullable<decimal> _MAT_MARKET_SHARE_P;
		
		private System.Nullable<decimal> _YTD_MARKET_SHARE_P;
		
		private System.Nullable<decimal> _LM_MARKET_SHARE_P;
		
		private System.Nullable<decimal> _MAT_MARKET_SHARE_L;
		
		private System.Nullable<decimal> _YTD_MARKET_SHARE_L;
		
		private System.Nullable<decimal> _LM_MARKET_SHARE_L;
		
		private System.Nullable<decimal> _MAT_GROUTH_C;
		
		private System.Nullable<decimal> _YTD_GROUTH_C;
		
		private System.Nullable<decimal> _LM_GROUTH_C;
		
		private System.Nullable<decimal> _MAT_GROUTH_JJ;
		
		private System.Nullable<decimal> _YTD_GROUTH_JJ;
		
		private System.Nullable<decimal> _LM_GROUTH_JJ;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_CHART_BY_CHANNEL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT MARKET SIZE]", Storage="_MAT_MARKET_SIZE", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> MAT_MARKET_SIZE
		{
			get
			{
				return this._MAT_MARKET_SIZE;
			}
			set
			{
				if ((this._MAT_MARKET_SIZE != value))
				{
					this._MAT_MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT MARKET SHARE P]", Storage="_MAT_MARKET_SHARE_P", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> MAT_MARKET_SHARE_P
		{
			get
			{
				return this._MAT_MARKET_SHARE_P;
			}
			set
			{
				if ((this._MAT_MARKET_SHARE_P != value))
				{
					this._MAT_MARKET_SHARE_P = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD MARKET SHARE P]", Storage="_YTD_MARKET_SHARE_P", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> YTD_MARKET_SHARE_P
		{
			get
			{
				return this._YTD_MARKET_SHARE_P;
			}
			set
			{
				if ((this._YTD_MARKET_SHARE_P != value))
				{
					this._YTD_MARKET_SHARE_P = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LM MARKET SHARE P]", Storage="_LM_MARKET_SHARE_P", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> LM_MARKET_SHARE_P
		{
			get
			{
				return this._LM_MARKET_SHARE_P;
			}
			set
			{
				if ((this._LM_MARKET_SHARE_P != value))
				{
					this._LM_MARKET_SHARE_P = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT MARKET SHARE L]", Storage="_MAT_MARKET_SHARE_L", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> MAT_MARKET_SHARE_L
		{
			get
			{
				return this._MAT_MARKET_SHARE_L;
			}
			set
			{
				if ((this._MAT_MARKET_SHARE_L != value))
				{
					this._MAT_MARKET_SHARE_L = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD MARKET SHARE L]", Storage="_YTD_MARKET_SHARE_L", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> YTD_MARKET_SHARE_L
		{
			get
			{
				return this._YTD_MARKET_SHARE_L;
			}
			set
			{
				if ((this._YTD_MARKET_SHARE_L != value))
				{
					this._YTD_MARKET_SHARE_L = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LM MARKET SHARE L]", Storage="_LM_MARKET_SHARE_L", DbType="Decimal(8,1)")]
		public System.Nullable<decimal> LM_MARKET_SHARE_L
		{
			get
			{
				return this._LM_MARKET_SHARE_L;
			}
			set
			{
				if ((this._LM_MARKET_SHARE_L != value))
				{
					this._LM_MARKET_SHARE_L = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT GROUTH C]", Storage="_MAT_GROUTH_C", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> MAT_GROUTH_C
		{
			get
			{
				return this._MAT_GROUTH_C;
			}
			set
			{
				if ((this._MAT_GROUTH_C != value))
				{
					this._MAT_GROUTH_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD GROUTH C]", Storage="_YTD_GROUTH_C", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> YTD_GROUTH_C
		{
			get
			{
				return this._YTD_GROUTH_C;
			}
			set
			{
				if ((this._YTD_GROUTH_C != value))
				{
					this._YTD_GROUTH_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LM GROUTH C]", Storage="_LM_GROUTH_C", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LM_GROUTH_C
		{
			get
			{
				return this._LM_GROUTH_C;
			}
			set
			{
				if ((this._LM_GROUTH_C != value))
				{
					this._LM_GROUTH_C = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT GROUTH JJ]", Storage="_MAT_GROUTH_JJ", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> MAT_GROUTH_JJ
		{
			get
			{
				return this._MAT_GROUTH_JJ;
			}
			set
			{
				if ((this._MAT_GROUTH_JJ != value))
				{
					this._MAT_GROUTH_JJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD GROUTH JJ]", Storage="_YTD_GROUTH_JJ", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> YTD_GROUTH_JJ
		{
			get
			{
				return this._YTD_GROUTH_JJ;
			}
			set
			{
				if ((this._YTD_GROUTH_JJ != value))
				{
					this._YTD_GROUTH_JJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[LM GROUTH JJ]", Storage="_LM_GROUTH_JJ", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LM_GROUTH_JJ
		{
			get
			{
				return this._LM_GROUTH_JJ;
			}
			set
			{
				if ((this._LM_GROUTH_JJ != value))
				{
					this._LM_GROUTH_JJ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHARTS_YTD")]
	public partial class v_CHARTS_YTD
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private string _NAME;
		
		private System.Nullable<decimal> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHARTS_YTD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(4000)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHARTS_LM")]
	public partial class v_CHARTS_LM
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private string _NAME;
		
		private System.Nullable<decimal> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHARTS_LM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(4000)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHART_PBP_FRANCHISE")]
	public partial class v_CHART_PBP_FRANCHISE
	{
		
		private decimal _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private decimal _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHART_PBP_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0) NOT NULL")]
		public decimal GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_CATEGORY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_J_J", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHARTS_PBP")]
	public partial class v_CHARTS_PBP
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private string _NAME;
		
		private System.Nullable<double> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHARTS_PBP()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(4000)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Float")]
		public System.Nullable<double> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_CATEGORY", DbType="Decimal(11,2)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUTH_J_J", DbType="Decimal(11,2)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_CHARTS_MAT_MARKET")]
	public partial class v_CHARTS_MAT_MARKET
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private string _NAME;
		
		private System.Nullable<decimal> _MARKET_SIZE;
		
		private System.Nullable<decimal> _PREVIOUS;
		
		private System.Nullable<decimal> _LATEST;
		
		private System.Nullable<decimal> _GROUTH_CATEGORY;
		
		private System.Nullable<decimal> _GROUTH_J_J;
		
		private string _TYPE;
		
		private string _CHART;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_CHARTS_MAT_MARKET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(4000)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MARKET SIZE]", Storage="_MARKET_SIZE", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> MARKET_SIZE
		{
			get
			{
				return this._MARKET_SIZE;
			}
			set
			{
				if ((this._MARKET_SIZE != value))
				{
					this._MARKET_SIZE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVIOUS", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PREVIOUS
		{
			get
			{
				return this._PREVIOUS;
			}
			set
			{
				if ((this._PREVIOUS != value))
				{
					this._PREVIOUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LATEST", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> LATEST
		{
			get
			{
				return this._LATEST;
			}
			set
			{
				if ((this._LATEST != value))
				{
					this._LATEST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH CATEGORY]", Storage="_GROUTH_CATEGORY", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_CATEGORY
		{
			get
			{
				return this._GROUTH_CATEGORY;
			}
			set
			{
				if ((this._GROUTH_CATEGORY != value))
				{
					this._GROUTH_CATEGORY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUTH J&J]", Storage="_GROUTH_J_J", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> GROUTH_J_J
		{
			get
			{
				return this._GROUTH_J_J;
			}
			set
			{
				if ((this._GROUTH_J_J != value))
				{
					this._GROUTH_J_J = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHART", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CHART
		{
			get
			{
				return this._CHART;
			}
			set
			{
				if ((this._CHART != value))
				{
					this._CHART = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
