#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_TOTAL> v_WRK_MARKET_TOTAL
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_TOTAL>();
			}
		}
		
		public System.Data.Linq.Table<v_MARKET_GROUPS_TOTAL> v_MARKET_GROUPS_TOTAL
		{
			get
			{
				return this.GetTable<v_MARKET_GROUPS_TOTAL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BOY> v_WRK_MARKET_BOY
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BOY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_PCVSPY> v_WRK_MARKET_PCVSPY
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_PCVSPY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_TOTAL_CUSTOM> v_WRK_MARKET_TOTAL_CUSTOM
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_TOTAL_CUSTOM>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MAT> v_WRK_BRAND_MAT
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MAT>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_PCVSPY> v_WRK_BRAND_PCVSPY
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_PCVSPY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BOY> v_WRK_BRAND_BOY
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BOY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_TOTAL> v_WRK_BRAND_TOTAL
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_TOTAL>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_YTD> v_WRK_BRAND_YTD
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_YTD>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_YTD> v_WRK_MARKET_YTD
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_YTD>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MAT> v_WRK_MARKET_MAT
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MAT>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BTG> v_WRK_MARKET_BTG
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BTG>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MONTH> v_WRK_MARKET_MONTH
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MONTH>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KPI> v_WRK_KPI
		{
			get
			{
				return this.GetTable<v_WRK_KPI>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_TOTAL_CUSTOM> v_WRK_BRAND_TOTAL_CUSTOM
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_TOTAL_CUSTOM>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MONTH> v_WRK_BRAND_MONTHs
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MONTH>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BTG> v_WRK_BRAND_BTGs
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BTG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_TOTAL")]
	public partial class v_WRK_MARKET_TOTAL
	{
		
		private decimal _MARKET;
		
		private decimal _BRAND;
		
		private System.Nullable<decimal> @__2012;
		
		private System.Nullable<decimal> @__2013;
		
		public v_WRK_MARKET_TOTAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(18,0) NOT NULL")]
		public decimal MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2012]", Storage="__2012", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> _2012
		{
			get
			{
				return this.@__2012;
			}
			set
			{
				if ((this.@__2012 != value))
				{
					this.@__2012 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2013]", Storage="__2013", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> _2013
		{
			get
			{
				return this.@__2013;
			}
			set
			{
				if ((this.@__2013 != value))
				{
					this.@__2013 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_MARKET_GROUPS_TOTAL")]
	public partial class v_MARKET_GROUPS_TOTAL
	{
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private decimal _BRAND;
		
		private System.Nullable<decimal> _YTD;
		
		private System.Nullable<decimal> _YEAR;
		
		private string _GROUP_NAME;
		
		private string _MARKET_NAME;
		
		private string _BRAND_NAME;
		
		public v_MARKET_GROUPS_TOTAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YTD
		{
			get
			{
				return this._YTD;
			}
			set
			{
				if ((this._YTD != value))
				{
					this._YTD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_NAME", DbType="VarChar(255)")]
		public string GROUP_NAME
		{
			get
			{
				return this._GROUP_NAME;
			}
			set
			{
				if ((this._GROUP_NAME != value))
				{
					this._GROUP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET_NAME", DbType="NVarChar(255)")]
		public string MARKET_NAME
		{
			get
			{
				return this._MARKET_NAME;
			}
			set
			{
				if ((this._MARKET_NAME != value))
				{
					this._MARKET_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND_NAME", DbType="NVarChar(255)")]
		public string BRAND_NAME
		{
			get
			{
				return this._BRAND_NAME;
			}
			set
			{
				if ((this._BRAND_NAME != value))
				{
					this._BRAND_NAME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BOY")]
	public partial class v_WRK_MARKET_BOY
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private decimal _MARKET;
		
		private decimal _BRAND;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		public v_WRK_MARKET_BOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(18,0) NOT NULL")]
		public decimal MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_PCVSPY")]
	public partial class v_WRK_MARKET_PCVSPY
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_PCVSPY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_TOTAL_CUSTOM")]
	public partial class v_WRK_MARKET_TOTAL_CUSTOM
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_TOTAL_CUSTOM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MAT")]
	public partial class v_WRK_BRAND_MAT
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MAT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(5,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_PCVSPY")]
	public partial class v_WRK_BRAND_PCVSPY
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_PCVSPY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BOY")]
	public partial class v_WRK_BRAND_BOY
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_TOTAL")]
	public partial class v_WRK_BRAND_TOTAL
	{
		
		private decimal _MARKET;
		
		private decimal _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_TOTAL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(18,0) NOT NULL")]
		public decimal MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(18,0) NOT NULL")]
		public decimal BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_YTD")]
	public partial class v_WRK_BRAND_YTD
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _YTD_COL1;
		
		private System.Nullable<decimal> _YTD_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_YTD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL1]", Storage="_YTD_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL1
		{
			get
			{
				return this._YTD_COL1;
			}
			set
			{
				if ((this._YTD_COL1 != value))
				{
					this._YTD_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL2]", Storage="_YTD_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL2
		{
			get
			{
				return this._YTD_COL2;
			}
			set
			{
				if ((this._YTD_COL2 != value))
				{
					this._YTD_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_YTD")]
	public partial class v_WRK_MARKET_YTD
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _YTD_COL1;
		
		private System.Nullable<decimal> _YTD_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_YTD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL1]", Storage="_YTD_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL1
		{
			get
			{
				return this._YTD_COL1;
			}
			set
			{
				if ((this._YTD_COL1 != value))
				{
					this._YTD_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YTD COL2]", Storage="_YTD_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD_COL2
		{
			get
			{
				return this._YTD_COL2;
			}
			set
			{
				if ((this._YTD_COL2 != value))
				{
					this._YTD_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MAT")]
	public partial class v_WRK_MARKET_MAT
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _MAT_COL1;
		
		private System.Nullable<decimal> _MAT_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MAT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL1]", Storage="_MAT_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL1
		{
			get
			{
				return this._MAT_COL1;
			}
			set
			{
				if ((this._MAT_COL1 != value))
				{
					this._MAT_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MAT COL2]", Storage="_MAT_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT_COL2
		{
			get
			{
				return this._MAT_COL2;
			}
			set
			{
				if ((this._MAT_COL2 != value))
				{
					this._MAT_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BTG")]
	public partial class v_WRK_MARKET_BTG
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _BTG_COL1;
		
		private System.Nullable<double> _BTG_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_BTG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BTG COL1]", Storage="_BTG_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> BTG_COL1
		{
			get
			{
				return this._BTG_COL1;
			}
			set
			{
				if ((this._BTG_COL1 != value))
				{
					this._BTG_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BTG COL2]", Storage="_BTG_COL2", DbType="Float")]
		public System.Nullable<double> BTG_COL2
		{
			get
			{
				return this._BTG_COL2;
			}
			set
			{
				if ((this._BTG_COL2 != value))
				{
					this._BTG_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MONTH")]
	public partial class v_WRK_MARKET_MONTH
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _MONTH_COL1;
		
		private System.Nullable<decimal> _MONTH_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MONTH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL1]", Storage="_MONTH_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL1
		{
			get
			{
				return this._MONTH_COL1;
			}
			set
			{
				if ((this._MONTH_COL1 != value))
				{
					this._MONTH_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL2]", Storage="_MONTH_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL2
		{
			get
			{
				return this._MONTH_COL2;
			}
			set
			{
				if ((this._MONTH_COL2 != value))
				{
					this._MONTH_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KPI")]
	public partial class v_WRK_KPI
	{
		
		private System.Nullable<decimal> _ID;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _KPI;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<double> _COL3;
		
		private string _KPI_COLUMN;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KPI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KPI
		{
			get
			{
				return this._KPI;
			}
			set
			{
				if ((this._KPI != value))
				{
					this._KPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Float")]
		public System.Nullable<double> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[KPI COLUMN]", Storage="_KPI_COLUMN", DbType="NVarChar(255)")]
		public string KPI_COLUMN
		{
			get
			{
				return this._KPI_COLUMN;
			}
			set
			{
				if ((this._KPI_COLUMN != value))
				{
					this._KPI_COLUMN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_TOTAL_CUSTOM")]
	public partial class v_WRK_BRAND_TOTAL_CUSTOM
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_TOTAL_CUSTOM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MONTH")]
	public partial class v_WRK_BRAND_MONTH
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _MONTH_COL1;
		
		private System.Nullable<decimal> _MONTH_COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MONTH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL1]", Storage="_MONTH_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL1
		{
			get
			{
				return this._MONTH_COL1;
			}
			set
			{
				if ((this._MONTH_COL1 != value))
				{
					this._MONTH_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH COL2]", Storage="_MONTH_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH_COL2
		{
			get
			{
				return this._MONTH_COL2;
			}
			set
			{
				if ((this._MONTH_COL2 != value))
				{
					this._MONTH_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BTG")]
	public partial class v_WRK_BRAND_BTG
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _GROUP_ORDER;
		
		private System.Nullable<decimal> _GROUP;
		
		private System.Nullable<decimal> _MARKET;
		
		private System.Nullable<decimal> _BRAND;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BTG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUP_ORDER", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> GROUP_ORDER
		{
			get
			{
				return this._GROUP_ORDER;
			}
			set
			{
				if ((this._GROUP_ORDER != value))
				{
					this._GROUP_ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this._GROUP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKET", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> MARKET
		{
			get
			{
				return this._MARKET;
			}
			set
			{
				if ((this._MARKET != value))
				{
					this._MARKET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRAND", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> BRAND
		{
			get
			{
				return this._BRAND;
			}
			set
			{
				if ((this._BRAND != value))
				{
					this._BRAND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
