<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VM22078D0\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_WRK_MARKET_TOTAL" Member="v_WRK_MARKET_TOTAL">
    <Type Name="v_WRK_MARKET_TOTAL">
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[2012]" Member="_2012" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[2013]" Member="_2013" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_MARKET_GROUPS_TOTAL" Member="v_MARKET_GROUPS_TOTAL">
    <Type Name="v_MARKET_GROUPS_TOTAL">
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="YTD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="YEAR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MARKET_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_BOY" Member="v_WRK_MARKET_BOY">
    <Type Name="v_WRK_MARKET_BOY">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_PCVSPY" Member="v_WRK_MARKET_PCVSPY">
    <Type Name="v_WRK_MARKET_PCVSPY">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_TOTAL_CUSTOM" Member="v_WRK_MARKET_TOTAL_CUSTOM">
    <Type Name="v_WRK_MARKET_TOTAL_CUSTOM">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_MAT" Member="v_WRK_BRAND_MAT">
    <Type Name="v_WRK_BRAND_MAT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(5,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_PCVSPY" Member="v_WRK_BRAND_PCVSPY">
    <Type Name="v_WRK_BRAND_PCVSPY">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_BOY" Member="v_WRK_BRAND_BOY">
    <Type Name="v_WRK_BRAND_BOY">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_TOTAL" Member="v_WRK_BRAND_TOTAL">
    <Type Name="v_WRK_BRAND_TOTAL">
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_YTD" Member="v_WRK_BRAND_YTD">
    <Type Name="v_WRK_BRAND_YTD">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_YTD" Member="v_WRK_MARKET_YTD">
    <Type Name="v_WRK_MARKET_YTD">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_MAT" Member="v_WRK_MARKET_MAT">
    <Type Name="v_WRK_MARKET_MAT">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_BTG" Member="v_WRK_MARKET_BTG">
    <Type Name="v_WRK_MARKET_BTG">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[BTG COL1]" Member="BTG_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BTG COL2]" Member="BTG_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_MARKET_MONTH" Member="v_WRK_MARKET_MONTH">
    <Type Name="v_WRK_MARKET_MONTH">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KPI" Member="v_WRK_KPI">
    <Type Name="v_WRK_KPI">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="KPI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,6)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[KPI COLUMN]" Member="KPI_COLUMN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_TOTAL_CUSTOM" Member="v_WRK_BRAND_TOTAL_CUSTOM">
    <Type Name="v_WRK_BRAND_TOTAL_CUSTOM">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_MONTH" Member="v_WRK_BRAND_MONTHs">
    <Type Name="v_WRK_BRAND_MONTH">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_BRAND_BTG" Member="v_WRK_BRAND_BTGs">
    <Type Name="v_WRK_BRAND_BTG">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>