#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class FranchiseDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public FranchiseDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FranchiseDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FranchiseDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FranchiseDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FranchiseDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BTG_FRANCHISE> v_WRK_BRAND_BTG_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BTG_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_BOY_FRANCHISE> v_WRK_BRAND_BOY_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_BOY_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MAT_FRANCHISE> v_WRK_BRAND_MAT_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MAT_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_MONTH_FRANCHISE> v_WRK_BRAND_MONTH_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_MONTH_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_PCVSPY_FRANCHISE> v_WRK_BRAND_PCVSPY_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_PCVSPY_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE> v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_BRAND_YTD_FRANCHISE> v_WRK_BRAND_YTD_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_BRAND_YTD_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BOY_FRANCHISE> v_WRK_MARKET_BOY_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BOY_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_BTG_FRANCHISE> v_WRK_MARKET_BTG_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_BTG_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MAT_FRANCHISE> v_WRK_MARKET_MAT_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MAT_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_MONTH_FRANCHISE> v_WRK_MARKET_MONTH_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_MONTH_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_PCVSPY_FRANCHISE> v_WRK_MARKET_PCVSPY_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_PCVSPY_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE> v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_MARKET_YTD_FRANCHISE> v_WRK_MARKET_YTD_FRANCHISE
		{
			get
			{
				return this.GetTable<v_WRK_MARKET_YTD_FRANCHISE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_FRANCHISE_DATA> v_WRK_FRANCHISE_DATA
		{
			get
			{
				return this.GetTable<v_WRK_FRANCHISE_DATA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BTG_FRANCHISE")]
	public partial class v_WRK_BRAND_BTG_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BTG_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_BOY_FRANCHISE")]
	public partial class v_WRK_BRAND_BOY_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<double> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<double> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_BOY_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Float")]
		public System.Nullable<double> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Float")]
		public System.Nullable<double> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MAT_FRANCHISE")]
	public partial class v_WRK_BRAND_MAT_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MAT_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_MONTH_FRANCHISE")]
	public partial class v_WRK_BRAND_MONTH_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_MONTH_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_PCVSPY_FRANCHISE")]
	public partial class v_WRK_BRAND_PCVSPY_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_PCVSPY_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE")]
	public partial class v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_TOTAL_CUSTOM_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_BRAND_YTD_FRANCHISE")]
	public partial class v_WRK_BRAND_YTD_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_BRAND_YTD_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BOY_FRANCHISE")]
	public partial class v_WRK_MARKET_BOY_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_BOY_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_BTG_FRANCHISE")]
	public partial class v_WRK_MARKET_BTG_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_BTG_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MAT_FRANCHISE")]
	public partial class v_WRK_MARKET_MAT_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MAT_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_MONTH_FRANCHISE")]
	public partial class v_WRK_MARKET_MONTH_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_MONTH_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_PCVSPY_FRANCHISE")]
	public partial class v_WRK_MARKET_PCVSPY_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<double> _INTERNAL;
		
		private System.Nullable<double> _LE;
		
		private System.Nullable<double> _PBP;
		
		private System.Nullable<decimal> _PCVSPY_COL1;
		
		private System.Nullable<decimal> _PCVSPY_COL2;
		
		private System.Nullable<decimal> _PCVSPY_COL3;
		
		private System.Nullable<decimal> _PCVSPY_COL4;
		
		private System.Nullable<decimal> _PCVSPY_COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_PCVSPY_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNAL", DbType="Float")]
		public System.Nullable<double> INTERNAL
		{
			get
			{
				return this._INTERNAL;
			}
			set
			{
				if ((this._INTERNAL != value))
				{
					this._INTERNAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE", DbType="Float")]
		public System.Nullable<double> LE
		{
			get
			{
				return this._LE;
			}
			set
			{
				if ((this._LE != value))
				{
					this._LE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PBP", DbType="Float")]
		public System.Nullable<double> PBP
		{
			get
			{
				return this._PBP;
			}
			set
			{
				if ((this._PBP != value))
				{
					this._PBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL1]", Storage="_PCVSPY_COL1", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL1
		{
			get
			{
				return this._PCVSPY_COL1;
			}
			set
			{
				if ((this._PCVSPY_COL1 != value))
				{
					this._PCVSPY_COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL2]", Storage="_PCVSPY_COL2", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL2
		{
			get
			{
				return this._PCVSPY_COL2;
			}
			set
			{
				if ((this._PCVSPY_COL2 != value))
				{
					this._PCVSPY_COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL3]", Storage="_PCVSPY_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL3
		{
			get
			{
				return this._PCVSPY_COL3;
			}
			set
			{
				if ((this._PCVSPY_COL3 != value))
				{
					this._PCVSPY_COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL4]", Storage="_PCVSPY_COL4", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL4
		{
			get
			{
				return this._PCVSPY_COL4;
			}
			set
			{
				if ((this._PCVSPY_COL4 != value))
				{
					this._PCVSPY_COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PCVSPY COL5]", Storage="_PCVSPY_COL5", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY_COL5
		{
			get
			{
				return this._PCVSPY_COL5;
			}
			set
			{
				if ((this._PCVSPY_COL5 != value))
				{
					this._PCVSPY_COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE")]
	public partial class v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _THREE_AGO;
		
		private System.Nullable<decimal> _TWO_AGO;
		
		private System.Nullable<decimal> _LAST;
		
		private System.Nullable<decimal> _CURRENT;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_TOTAL_CUSTOM_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[THREE AGO]", Storage="_THREE_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> THREE_AGO
		{
			get
			{
				return this._THREE_AGO;
			}
			set
			{
				if ((this._THREE_AGO != value))
				{
					this._THREE_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TWO AGO]", Storage="_TWO_AGO", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TWO_AGO
		{
			get
			{
				return this._TWO_AGO;
			}
			set
			{
				if ((this._TWO_AGO != value))
				{
					this._TWO_AGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> LAST
		{
			get
			{
				return this._LAST;
			}
			set
			{
				if ((this._LAST != value))
				{
					this._LAST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENT]", Storage="_CURRENT", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> CURRENT
		{
			get
			{
				return this._CURRENT;
			}
			set
			{
				if ((this._CURRENT != value))
				{
					this._CURRENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_MARKET_YTD_FRANCHISE")]
	public partial class v_WRK_MARKET_YTD_FRANCHISE
	{
		
		private decimal _PARENT_ID;
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_MARKET_YTD_FRANCHISE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_FRANCHISE_DATA")]
	public partial class v_WRK_FRANCHISE_DATA
	{
		
		private System.Nullable<decimal> _ORDER;
		
		private decimal _ID;
		
		private System.Nullable<decimal> _PARENT_ID;
		
		private string _NAME;
		
		private string _HAS_CHILD;
		
		public v_WRK_FRANCHISE_DATA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ORDER]", Storage="_ORDER", DbType="Decimal(24,0)")]
		public System.Nullable<decimal> ORDER
		{
			get
			{
				return this._ORDER;
			}
			set
			{
				if ((this._ORDER != value))
				{
					this._ORDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PARENT_ID
		{
			get
			{
				return this._PARENT_ID;
			}
			set
			{
				if ((this._PARENT_ID != value))
				{
					this._PARENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HAS_CHILD", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string HAS_CHILD
		{
			get
			{
				return this._HAS_CHILD;
			}
			set
			{
				if ((this._HAS_CHILD != value))
				{
					this._HAS_CHILD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
