<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="GodzillaWRKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VM22078D0\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WRK_BOY_BASIC_DATA" Member="WRK_BOY_BASIC_DATAs">
    <Type Name="WRK_BOY_BASIC_DATA">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(261)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE COL2]" Member="SHARE_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SHARE PC]" Member="SHARE_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE1]" Member="CONVERSION_RATE1" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE2]" Member="CONVERSION_RATE2" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_YTD_FRANCHISE" Member="WRK_MARKET_YTD_FRANCHISEs">
    <Type Name="WRK_MARKET_YTD_FRANCHISE">
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BOY_CALC_DATA" Member="WRK_BOY_CALC_DATAs">
    <Type Name="WRK_BOY_CALC_DATA">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(261)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="[MARKET COL]" Member="MARKET_COL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC TYPE]" Member="MARKET_PC_TYPE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL]" Member="SELLOUT_COL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT PC TYPE]" Member="SELLOUT_PC_TYPE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL]" Member="SELLIN_COL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN PC TYPE]" Member="SELLIN_PC_TYPE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLIN PC INT]" Member="SELLIN_PC_INT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[LAST DATE]" Member="LAST_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SESSION" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BOY_CALC_DATA_TOTAL" Member="WRK_BOY_CALC_DATA_TOTALs">
    <Type Name="WRK_BOY_CALC_DATA_TOTAL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NTS_ORDER" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="[BRAND NAME]" Member="BRAND_NAME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NTS_NAME" Type="System.String" DbType="NVarChar(267)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="[MARKET COL]" Member="MARKET_COL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET TYPE]" Member="MARKET_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET YTD]" Member="MARKET_YTD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT YTD]" Member="SELLOUT_YTD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN YTD]" Member="SELLIN_YTD" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MARKET COL1]" Member="MARKET_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET COL2]" Member="MARKET_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL]" Member="SELLOUT_COL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLOUT TYPE]" Member="SELLOUT_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL1]" Member="SELLOUT_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT COL2]" Member="SELLOUT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL]" Member="SELLIN_COL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[SELLIN TYPE]" Member="SELLIN_TYPE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL1]" Member="SELLIN_COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN COL2]" Member="SELLIN_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC]" Member="MARKET_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SHARE TOTAL]" Member="SHARE_TOTAL" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SHARE COL1]" Member="SHARE_COL1" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SHARE PC]" Member="SHARE_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PC]" Member="SELLOUT_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLIN PC]" Member="SELLIN_PC" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[CONVERSION RATE]" Member="CONVERSION_RATE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MARKET DIFF]" Member="MARKET_DIFF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLOUT DIFF]" Member="SELLOUT_DIFF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[SELLIN DIFF]" Member="SELLIN_DIFF" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[MARKET PC INT]" Member="MARKET_PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLOUT PC INT]" Member="SELLOUT_PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SELLIN PC INT]" Member="SELLIN_PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[SHARE PC INT]" Member="SHARE_PC_INT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="[MARKET ID]" Member="MARKET_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLOUT ID]" Member="SELLOUT_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[SELLIN ID]" Member="SELLIN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BOY" Member="WRK_BRAND_BOYs">
    <Type Name="WRK_BRAND_BOY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BOY_CHANNEL" Member="WRK_BRAND_BOY_CHANNELs">
    <Type Name="WRK_BRAND_BOY_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BOY_FRANCHISE" Member="WRK_BRAND_BOY_FRANCHISEs">
    <Type Name="WRK_BRAND_BOY_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BTG" Member="WRK_BRAND_BTGs">
    <Type Name="WRK_BRAND_BTG">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BTG_CHANNEL" Member="WRK_BRAND_BTG_CHANNELs">
    <Type Name="WRK_BRAND_BTG_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BTG_FRANCHISE" Member="WRK_BRAND_BTG_FRANCHISEs">
    <Type Name="WRK_BRAND_BTG_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BY_CHANNEL" Member="WRK_BRAND_BY_CHANNELs">
    <Type Name="WRK_BRAND_BY_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL1]" Member="TOTAL_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL2]" Member="TOTAL_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BY_CUSTOM_GROUP" Member="WRK_BRAND_BY_CUSTOM_GROUPs">
    <Type Name="WRK_BRAND_BY_CUSTOM_GROUP">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL1]" Member="TOTAL_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL2]" Member="TOTAL_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_BY_SUPER" Member="WRK_BRAND_BY_SUPERs">
    <Type Name="WRK_BRAND_BY_SUPER">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SUPER" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL1]" Member="TOTAL_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL COL2]" Member="TOTAL_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MAT" Member="WRK_BRAND_MATs">
    <Type Name="WRK_BRAND_MAT">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(5,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MAT_CHANNEL" Member="WRK_BRAND_MAT_CHANNELs">
    <Type Name="WRK_BRAND_MAT_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(5,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MAT_FRANCHISE" Member="WRK_BRAND_MAT_FRANCHISEs">
    <Type Name="WRK_BRAND_MAT_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MONTH" Member="WRK_BRAND_MONTHs">
    <Type Name="WRK_BRAND_MONTH">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MONTH_CHANNEL" Member="WRK_BRAND_MONTH_CHANNELs">
    <Type Name="WRK_BRAND_MONTH_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_MONTH_FRANCHISE" Member="WRK_BRAND_MONTH_FRANCHISEs">
    <Type Name="WRK_BRAND_MONTH_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_PCVSPY" Member="WRK_BRAND_PCVSPies">
    <Type Name="WRK_BRAND_PCVSPY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_PCVSPY_CHANNEL" Member="WRK_BRAND_PCVSPY_CHANNELs">
    <Type Name="WRK_BRAND_PCVSPY_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_PCVSPY_FRANCHISE" Member="WRK_BRAND_PCVSPY_FRANCHISEs">
    <Type Name="WRK_BRAND_PCVSPY_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_TOTAL" Member="WRK_BRAND_TOTALs">
    <Type Name="WRK_BRAND_TOTAL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_TOTAL_CUSTOM" Member="WRK_BRAND_TOTAL_CUSTOMs">
    <Type Name="WRK_BRAND_TOTAL_CUSTOM">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_TOTAL_CUSTOM_CHANNEL" Member="WRK_BRAND_TOTAL_CUSTOM_CHANNELs">
    <Type Name="WRK_BRAND_TOTAL_CUSTOM_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_TOTAL_CUSTOM_FRANCHISE" Member="WRK_BRAND_TOTAL_CUSTOM_FRANCHISEs">
    <Type Name="WRK_BRAND_TOTAL_CUSTOM_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_YTD" Member="WRK_BRAND_YTDs">
    <Type Name="WRK_BRAND_YTD">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_YTD_CHANNEL" Member="WRK_BRAND_YTD_CHANNELs">
    <Type Name="WRK_BRAND_YTD_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_BRAND_YTD_FRANCHISE" Member="WRK_BRAND_YTD_FRANCHISEs">
    <Type Name="WRK_BRAND_YTD_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_KEYBRANDS_BASE" Member="WRK_KEYBRANDS_BASEs">
    <Type Name="WRK_KEYBRANDS_BASE">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(14,3)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BOY" Member="WRK_MARKET_BOYs">
    <Type Name="WRK_MARKET_BOY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BOY_CHANNEL" Member="WRK_MARKET_BOY_CHANNELs">
    <Type Name="WRK_MARKET_BOY_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BOY_FRANCHISE" Member="WRK_MARKET_BOY_FRANCHISEs">
    <Type Name="WRK_MARKET_BOY_FRANCHISE">
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BTG" Member="WRK_MARKET_BTGs">
    <Type Name="WRK_MARKET_BTG">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[BTG COL1]" Member="BTG_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BTG COL2]" Member="BTG_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BTG_CHANNEL" Member="WRK_MARKET_BTG_CHANNELs">
    <Type Name="WRK_MARKET_BTG_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[BTG COL1]" Member="BTG_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[BTG COL2]" Member="BTG_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_BTG_FRANCHISE" Member="WRK_MARKET_BTG_FRANCHISEs">
    <Type Name="WRK_MARKET_BTG_FRANCHISE">
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_GROUPS_CUSTOM" Member="WRK_MARKET_GROUPS_CUSTOMs">
    <Type Name="WRK_MARKET_GROUPS_CUSTOM">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="AU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="INTERNAL_TARGET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="YEAR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MAT" Member="WRK_MARKET_MATs">
    <Type Name="WRK_MARKET_MAT">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MAT_CHANNEL" Member="WRK_MARKET_MAT_CHANNELs">
    <Type Name="WRK_MARKET_MAT_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MAT COL1]" Member="MAT_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MAT COL2]" Member="MAT_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MAT_FRANCHISE" Member="WRK_MARKET_MAT_FRANCHISEs">
    <Type Name="WRK_MARKET_MAT_FRANCHISE">
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MONTH" Member="WRK_MARKET_MONTHs">
    <Type Name="WRK_MARKET_MONTH">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MONTH_CHANNEL" Member="WRK_MARKET_MONTH_CHANNELs">
    <Type Name="WRK_MARKET_MONTH_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[MONTH COL1]" Member="MONTH_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[MONTH COL2]" Member="MONTH_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_MONTH_FRANCHISE" Member="WRK_MARKET_MONTH_FRANCHISEs">
    <Type Name="WRK_MARKET_MONTH_FRANCHISE">
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_PCVSPY" Member="WRK_MARKET_PCVSPies">
    <Type Name="WRK_MARKET_PCVSPY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_PCVSPY_CHANNEL" Member="WRK_MARKET_PCVSPY_CHANNELs">
    <Type Name="WRK_MARKET_PCVSPY_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_PCVSPY_FRANCHISE" Member="WRK_MARKET_PCVSPY_FRANCHISEs">
    <Type Name="WRK_MARKET_PCVSPY_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="INTERNAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PBP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[PCVSPY COL1]" Member="PCVSPY_COL1" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL2]" Member="PCVSPY_COL2" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL3]" Member="PCVSPY_COL3" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL4]" Member="PCVSPY_COL4" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[PCVSPY COL5]" Member="PCVSPY_COL5" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_TOTAL" Member="WRK_MARKET_TOTALs">
    <Type Name="WRK_MARKET_TOTAL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_TOTAL_CUSTOM" Member="WRK_MARKET_TOTAL_CUSTOMs">
    <Type Name="WRK_MARKET_TOTAL_CUSTOM">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_TOTAL_CUSTOM_CHANNEL" Member="WRK_MARKET_TOTAL_CUSTOM_CHANNELs">
    <Type Name="WRK_MARKET_TOTAL_CUSTOM_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_TOTAL_CUSTOM_FRANCHISE" Member="WRK_MARKET_TOTAL_CUSTOM_FRANCHISEs">
    <Type Name="WRK_MARKET_TOTAL_CUSTOM_FRANCHISE">
      <Column Name="PARENT_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.Decimal" DbType="Decimal(24,0)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[THREE AGO]" Member="THREE_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TWO AGO]" Member="TWO_AGO" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="LAST" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[CURRENT]" Member="CURRENT" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_YTD" Member="WRK_MARKET_YTDs">
    <Type Name="WRK_MARKET_YTD">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_MARKET_YTD_CHANNEL" Member="WRK_MARKET_YTD_CHANNELs">
    <Type Name="WRK_MARKET_YTD_CHANNEL">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GROUP_ORDER" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MARKET" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRAND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[YTD COL1]" Member="YTD_COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YTD COL2]" Member="YTD_COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_KEYBRANDS_BOY" Member="WRK_KEYBRANDS_BOYs">
    <Type Name="WRK_KEYBRANDS_BOY">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_KEYBRANDS_BTG" Member="WRK_KEYBRANDS_BTGs">
    <Type Name="WRK_KEYBRANDS_BTG">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WRK_KEYBRANDS_PCVSPY" Member="WRK_KEYBRANDS_PCVSPies">
    <Type Name="WRK_KEYBRANDS_PCVSPY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DATA" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="COL5" Type="System.Decimal" DbType="Decimal(11,2)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>