<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="KeybrandsDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VM22078D0\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.v_WRK_KEYBRANDS_BASE" Member="v_WRK_KEYBRANDS_BASE">
    <Type Name="v_WRK_KEYBRANDS_BASE">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(14,3)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_TOTALS_DATA" Member="v_WRK_KEYBRANDS_TOTALS_DATA">
    <Type Name="v_WRK_KEYBRANDS_TOTALS_DATA">
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="PCVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_BOY" Member="v_WRK_KEYBRANDS_BOY">
    <Type Name="v_WRK_KEYBRANDS_BOY">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_BTG" Member="v_WRK_KEYBRANDS_BTG">
    <Type Name="v_WRK_KEYBRANDS_BTG">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PSVSPY" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_DATA" Member="v_WRK_KEYBRANDS_DATA">
    <Type Name="v_WRK_KEYBRANDS_DATA">
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOTAL" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MONTH1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="YTD1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MAT1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL+1]" Member="TOTAL_1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MONTH2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="YTD2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="MAT2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL-1]" Member="TOTAL_11" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[TOTAL-2]" Member="TOTAL_2" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_PCVSPY" Member="v_WRK_KEYBRANDS_PCVSPY">
    <Type Name="v_WRK_KEYBRANDS_PCVSPY">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="COL2" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="COL3" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="COL4" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="COL5" Type="System.Decimal" DbType="Decimal(10,1)" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_WRK_KEYBRANDS_TOTALS_BOY" Member="v_WRK_KEYBRANDS_TOTALS_BOY">
    <Type Name="v_WRK_KEYBRANDS_TOTALS_BOY">
      <Column Name="CHANNEL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DATA" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="COL1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="COL3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[YEAR PERIOD]" Member="YEAR_PERIOD" Type="System.Decimal" DbType="Decimal(19,0)" CanBeNull="true" />
      <Column Name="[MONTH PERIOD]" Member="MONTH_PERIOD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>