#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class KeybrandsDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public KeybrandsDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KeybrandsDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeybrandsDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeybrandsDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KeybrandsDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_BASE> v_WRK_KEYBRANDS_BASE
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_BASE>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_TOTALS_DATA> v_WRK_KEYBRANDS_TOTALS_DATA
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_TOTALS_DATA>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_BOY> v_WRK_KEYBRANDS_BOY
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_BOY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_BTG> v_WRK_KEYBRANDS_BTG
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_BTG>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_DATA> v_WRK_KEYBRANDS_DATA
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_DATA>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_PCVSPY> v_WRK_KEYBRANDS_PCVSPY
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_PCVSPY>();
			}
		}
		
		public System.Data.Linq.Table<v_WRK_KEYBRANDS_TOTALS_BOY> v_WRK_KEYBRANDS_TOTALS_BOY
		{
			get
			{
				return this.GetTable<v_WRK_KEYBRANDS_TOTALS_BOY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_BASE")]
	public partial class v_WRK_KEYBRANDS_BASE
	{
		
		private string _DATA;
		
		private string _TYPE;
		
		private System.Nullable<decimal> _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_BASE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(14,3)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_TOTALS_DATA")]
	public partial class v_WRK_KEYBRANDS_TOTALS_DATA
	{
		
		private System.Nullable<decimal> _CHANNEL;
		
		private string _DATA;
		
		private string _TYPE;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _PCVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_TOTALS_DATA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PCVSPY
		{
			get
			{
				return this._PCVSPY;
			}
			set
			{
				if ((this._PCVSPY != value))
				{
					this._PCVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_BOY")]
	public partial class v_WRK_KEYBRANDS_BOY
	{
		
		private string _DATA;
		
		private string _TYPE;
		
		private System.Nullable<decimal> _ID;
		
		private string _NAME;
		
		private System.Nullable<double> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<double> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_BOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(255)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Float")]
		public System.Nullable<double> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Float")]
		public System.Nullable<double> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_BTG")]
	public partial class v_WRK_KEYBRANDS_BTG
	{
		
		private string _DATA;
		
		private string _TYPE;
		
		private System.Nullable<decimal> _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<decimal> _PSVSPY;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_BTG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(255)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PSVSPY", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> PSVSPY
		{
			get
			{
				return this._PSVSPY;
			}
			set
			{
				if ((this._PSVSPY != value))
				{
					this._PSVSPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_DATA")]
	public partial class v_WRK_KEYBRANDS_DATA
	{
		
		private string _DATA;
		
		private System.Nullable<decimal> _ID;
		
		private string _NAME;
		
		private System.Nullable<decimal> _TOTAL;
		
		private System.Nullable<decimal> _MONTH1;
		
		private System.Nullable<decimal> _YTD1;
		
		private System.Nullable<decimal> _MAT1;
		
		private System.Nullable<decimal> _TOTAL_1;
		
		private System.Nullable<decimal> _MONTH2;
		
		private System.Nullable<decimal> _YTD2;
		
		private System.Nullable<decimal> _MAT2;
		
		private System.Nullable<decimal> _TOTAL_11;
		
		private System.Nullable<decimal> _TOTAL_2;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_DATA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this._TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTH1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH1
		{
			get
			{
				return this._MONTH1;
			}
			set
			{
				if ((this._MONTH1 != value))
				{
					this._MONTH1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTD1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD1
		{
			get
			{
				return this._YTD1;
			}
			set
			{
				if ((this._YTD1 != value))
				{
					this._YTD1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT1
		{
			get
			{
				return this._MAT1;
			}
			set
			{
				if ((this._MAT1 != value))
				{
					this._MAT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL+1]", Storage="_TOTAL_1", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL_1
		{
			get
			{
				return this._TOTAL_1;
			}
			set
			{
				if ((this._TOTAL_1 != value))
				{
					this._TOTAL_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONTH2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MONTH2
		{
			get
			{
				return this._MONTH2;
			}
			set
			{
				if ((this._MONTH2 != value))
				{
					this._MONTH2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YTD2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> YTD2
		{
			get
			{
				return this._YTD2;
			}
			set
			{
				if ((this._YTD2 != value))
				{
					this._YTD2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> MAT2
		{
			get
			{
				return this._MAT2;
			}
			set
			{
				if ((this._MAT2 != value))
				{
					this._MAT2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL-1]", Storage="_TOTAL_11", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL_11
		{
			get
			{
				return this._TOTAL_11;
			}
			set
			{
				if ((this._TOTAL_11 != value))
				{
					this._TOTAL_11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL-2]", Storage="_TOTAL_2", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> TOTAL_2
		{
			get
			{
				return this._TOTAL_2;
			}
			set
			{
				if ((this._TOTAL_2 != value))
				{
					this._TOTAL_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_PCVSPY")]
	public partial class v_WRK_KEYBRANDS_PCVSPY
	{
		
		private System.Nullable<decimal> _ID;
		
		private string _DATA;
		
		private string _TYPE;
		
		private string _NAME;
		
		private System.Nullable<decimal> _COL1;
		
		private System.Nullable<decimal> _COL2;
		
		private System.Nullable<decimal> _COL3;
		
		private System.Nullable<decimal> _COL4;
		
		private System.Nullable<decimal> _COL5;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_PCVSPY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(255)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL4", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL4
		{
			get
			{
				return this._COL4;
			}
			set
			{
				if ((this._COL4 != value))
				{
					this._COL4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL5", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> COL5
		{
			get
			{
				return this._COL5;
			}
			set
			{
				if ((this._COL5 != value))
				{
					this._COL5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_WRK_KEYBRANDS_TOTALS_BOY")]
	public partial class v_WRK_KEYBRANDS_TOTALS_BOY
	{
		
		private int _CHANNEL;
		
		private string _DATA;
		
		private string _TYPE;
		
		private System.Nullable<double> _COL1;
		
		private System.Nullable<double> _COL2;
		
		private System.Nullable<double> _COL3;
		
		private System.Nullable<decimal> _YEAR_PERIOD;
		
		private System.Nullable<decimal> _MONTH_PERIOD;
		
		public v_WRK_KEYBRANDS_TOTALS_BOY()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Int NOT NULL")]
		public int CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this._CHANNEL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string DATA
		{
			get
			{
				return this._DATA;
			}
			set
			{
				if ((this._DATA != value))
				{
					this._DATA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(255)")]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this._TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL1", DbType="Float")]
		public System.Nullable<double> COL1
		{
			get
			{
				return this._COL1;
			}
			set
			{
				if ((this._COL1 != value))
				{
					this._COL1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL2", DbType="Float")]
		public System.Nullable<double> COL2
		{
			get
			{
				return this._COL2;
			}
			set
			{
				if ((this._COL2 != value))
				{
					this._COL2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COL3", DbType="Float")]
		public System.Nullable<double> COL3
		{
			get
			{
				return this._COL3;
			}
			set
			{
				if ((this._COL3 != value))
				{
					this._COL3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[YEAR PERIOD]", Storage="_YEAR_PERIOD", DbType="Decimal(19,0)")]
		public System.Nullable<decimal> YEAR_PERIOD
		{
			get
			{
				return this._YEAR_PERIOD;
			}
			set
			{
				if ((this._YEAR_PERIOD != value))
				{
					this._YEAR_PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MONTH PERIOD]", Storage="_MONTH_PERIOD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MONTH_PERIOD
		{
			get
			{
				return this._MONTH_PERIOD;
			}
			set
			{
				if ((this._MONTH_PERIOD != value))
				{
					this._MONTH_PERIOD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
