#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrawmanApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="godzilla")]
	public partial class MenuDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMARKET_MASTER(MARKET_MASTER instance);
    partial void UpdateMARKET_MASTER(MARKET_MASTER instance);
    partial void DeleteMARKET_MASTER(MARKET_MASTER instance);
    partial void InsertMENU_CONFIG(MENU_CONFIG instance);
    partial void UpdateMENU_CONFIG(MENU_CONFIG instance);
    partial void DeleteMENU_CONFIG(MENU_CONFIG instance);
    #endregion
		
		public MenuDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["godzillaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MenuDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MARKET_MASTER> MARKET_MASTER
		{
			get
			{
				return this.GetTable<MARKET_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<MENU_CONFIG> MENU_CONFIG
		{
			get
			{
				return this.GetTable<MENU_CONFIG>();
			}
		}
		
		public System.Data.Linq.Table<v_MENU_MASTER> v_MENU_MASTER
		{
			get
			{
				return this.GetTable<v_MENU_MASTER>();
			}
		}
		
		public System.Data.Linq.Table<v_TAB_MASTER> v_TAB_MASTERs
		{
			get
			{
				return this.GetTable<v_TAB_MASTER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MARKET_MASTER")]
	public partial class MARKET_MASTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private System.Nullable<decimal> _GROUP;
		
		private string _NAME;
		
		private System.Nullable<decimal> _CHANNEL;
		
		private System.Nullable<decimal> _FRANCHISE;
		
		private System.Nullable<decimal> _KEYBRANDS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnGROUPChanging(System.Nullable<decimal> value);
    partial void OnGROUPChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnCHANNELChanging(System.Nullable<decimal> value);
    partial void OnCHANNELChanged();
    partial void OnFRANCHISEChanging(System.Nullable<decimal> value);
    partial void OnFRANCHISEChanged();
    partial void OnKEYBRANDSChanging(System.Nullable<decimal> value);
    partial void OnKEYBRANDSChanged();
    #endregion
		
		public MARKET_MASTER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[GROUP]", Storage="_GROUP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GROUP
		{
			get
			{
				return this._GROUP;
			}
			set
			{
				if ((this._GROUP != value))
				{
					this.OnGROUPChanging(value);
					this.SendPropertyChanging();
					this._GROUP = value;
					this.SendPropertyChanged("GROUP");
					this.OnGROUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANNEL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CHANNEL
		{
			get
			{
				return this._CHANNEL;
			}
			set
			{
				if ((this._CHANNEL != value))
				{
					this.OnCHANNELChanging(value);
					this.SendPropertyChanging();
					this._CHANNEL = value;
					this.SendPropertyChanged("CHANNEL");
					this.OnCHANNELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRANCHISE", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> FRANCHISE
		{
			get
			{
				return this._FRANCHISE;
			}
			set
			{
				if ((this._FRANCHISE != value))
				{
					this.OnFRANCHISEChanging(value);
					this.SendPropertyChanging();
					this._FRANCHISE = value;
					this.SendPropertyChanged("FRANCHISE");
					this.OnFRANCHISEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEYBRANDS", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> KEYBRANDS
		{
			get
			{
				return this._KEYBRANDS;
			}
			set
			{
				if ((this._KEYBRANDS != value))
				{
					this.OnKEYBRANDSChanging(value);
					this.SendPropertyChanging();
					this._KEYBRANDS = value;
					this.SendPropertyChanged("KEYBRANDS");
					this.OnKEYBRANDSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MENU_CONFIG")]
	public partial class MENU_CONFIG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _ID;
		
		private System.Nullable<decimal> _MENU_ID;
		
		private string _USER;
		
		private string _PERMISSION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(decimal value);
    partial void OnIDChanged();
    partial void OnMENU_IDChanging(System.Nullable<decimal> value);
    partial void OnMENU_IDChanged();
    partial void OnUSERChanging(string value);
    partial void OnUSERChanged();
    partial void OnPERMISSIONChanging(string value);
    partial void OnPERMISSIONChanged();
    #endregion
		
		public MENU_CONFIG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENU_ID", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MENU_ID
		{
			get
			{
				return this._MENU_ID;
			}
			set
			{
				if ((this._MENU_ID != value))
				{
					this.OnMENU_IDChanging(value);
					this.SendPropertyChanging();
					this._MENU_ID = value;
					this.SendPropertyChanged("MENU_ID");
					this.OnMENU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[USER]", Storage="_USER", DbType="NVarChar(255)")]
		public string USER
		{
			get
			{
				return this._USER;
			}
			set
			{
				if ((this._USER != value))
				{
					this.OnUSERChanging(value);
					this.SendPropertyChanging();
					this._USER = value;
					this.SendPropertyChanged("USER");
					this.OnUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERMISSION", DbType="NVarChar(2)")]
		public string PERMISSION
		{
			get
			{
				return this._PERMISSION;
			}
			set
			{
				if ((this._PERMISSION != value))
				{
					this.OnPERMISSIONChanging(value);
					this.SendPropertyChanging();
					this._PERMISSION = value;
					this.SendPropertyChanged("PERMISSION");
					this.OnPERMISSIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_MENU_MASTER")]
	public partial class v_MENU_MASTER
	{
		
		private decimal _ID;
		
		private string _NAME;
		
		private string _URL;
		
		private string _CONTROLLER;
		
		private System.Nullable<decimal> _PARENT;
		
		private string _PERMISSION;
		
		private string _USER;
		
		private string _DIVIDER_BEFORE;
		
		private string _DISABLED;
		
		public v_MENU_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(255)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(1024)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLLER", DbType="NVarChar(1024)")]
		public string CONTROLLER
		{
			get
			{
				return this._CONTROLLER;
			}
			set
			{
				if ((this._CONTROLLER != value))
				{
					this._CONTROLLER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PARENT
		{
			get
			{
				return this._PARENT;
			}
			set
			{
				if ((this._PARENT != value))
				{
					this._PARENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERMISSION", DbType="NVarChar(2)")]
		public string PERMISSION
		{
			get
			{
				return this._PERMISSION;
			}
			set
			{
				if ((this._PERMISSION != value))
				{
					this._PERMISSION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[USER]", Storage="_USER", DbType="NVarChar(255)")]
		public string USER
		{
			get
			{
				return this._USER;
			}
			set
			{
				if ((this._USER != value))
				{
					this._USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[DIVIDER BEFORE]", Storage="_DIVIDER_BEFORE", DbType="NVarChar(255)")]
		public string DIVIDER_BEFORE
		{
			get
			{
				return this._DIVIDER_BEFORE;
			}
			set
			{
				if ((this._DIVIDER_BEFORE != value))
				{
					this._DIVIDER_BEFORE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISABLED", DbType="NVarChar(1)")]
		public string DISABLED
		{
			get
			{
				return this._DISABLED;
			}
			set
			{
				if ((this._DISABLED != value))
				{
					this._DISABLED = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_TAB_MASTER")]
	public partial class v_TAB_MASTER
	{
		
		private string _NAME;
		
		private string _URL;
		
		private string _CONTROLLER;
		
		private string _SELECT_DEFAULT;
		
		private string _MENU_URL;
		
		private decimal _MENU_ID;
		
		private string _CURRENCY_ADJUST;
		
		private string _CURRENCY;
		
		private string _PC_ADJUST;
		
		private string _WC;
		
		private string _PERIOD;
		
		public v_TAB_MASTER()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="NVarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(255)")]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTROLLER", DbType="NVarChar(255)")]
		public string CONTROLLER
		{
			get
			{
				return this._CONTROLLER;
			}
			set
			{
				if ((this._CONTROLLER != value))
				{
					this._CONTROLLER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SELECT_DEFAULT", DbType="NVarChar(1)")]
		public string SELECT_DEFAULT
		{
			get
			{
				return this._SELECT_DEFAULT;
			}
			set
			{
				if ((this._SELECT_DEFAULT != value))
				{
					this._SELECT_DEFAULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MENU URL]", Storage="_MENU_URL", DbType="NVarChar(1024)")]
		public string MENU_URL
		{
			get
			{
				return this._MENU_URL;
			}
			set
			{
				if ((this._MENU_URL != value))
				{
					this._MENU_URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[MENU ID]", Storage="_MENU_ID", DbType="Decimal(18,0) NOT NULL")]
		public decimal MENU_ID
		{
			get
			{
				return this._MENU_ID;
			}
			set
			{
				if ((this._MENU_ID != value))
				{
					this._MENU_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CURRENCY ADJUST]", Storage="_CURRENCY_ADJUST", DbType="NVarChar(1)")]
		public string CURRENCY_ADJUST
		{
			get
			{
				return this._CURRENCY_ADJUST;
			}
			set
			{
				if ((this._CURRENCY_ADJUST != value))
				{
					this._CURRENCY_ADJUST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCY", DbType="NVarChar(1)")]
		public string CURRENCY
		{
			get
			{
				return this._CURRENCY;
			}
			set
			{
				if ((this._CURRENCY != value))
				{
					this._CURRENCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[PC ADJUST]", Storage="_PC_ADJUST", DbType="NVarChar(1)")]
		public string PC_ADJUST
		{
			get
			{
				return this._PC_ADJUST;
			}
			set
			{
				if ((this._PC_ADJUST != value))
				{
					this._PC_ADJUST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WC", DbType="NVarChar(1)")]
		public string WC
		{
			get
			{
				return this._WC;
			}
			set
			{
				if ((this._WC != value))
				{
					this._WC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIOD", DbType="NVarChar(1)")]
		public string PERIOD
		{
			get
			{
				return this._PERIOD;
			}
			set
			{
				if ((this._PERIOD != value))
				{
					this._PERIOD = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
