<?xml version="1.0" encoding="utf-8"?><Database Name="godzilla" Class="MenuDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=VM22078D0\SQLEXPRESS;Initial Catalog=godzilla;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="godzillaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MARKET_MASTER" Member="MARKET_MASTER">
    <Type Name="MARKET_MASTER">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[GROUP]" Member="GROUP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHANNEL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FRANCHISE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="KEYBRANDS" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MENU_CONFIG" Member="MENU_CONFIG">
    <Type Name="MENU_CONFIG">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MENU_ID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PERMISSION" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_MENU_MASTER" Member="v_MENU_MASTER">
    <Type Name="v_MENU_MASTER">
      <Column Name="ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="CONTROLLER" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="PARENT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PERMISSION" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="[USER]" Member="USER" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[DIVIDER BEFORE]" Member="DIVIDER_BEFORE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DISABLED" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_TAB_MASTER" Member="v_TAB_MASTERs">
    <Type Name="v_TAB_MASTER">
      <Column Name="NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONTROLLER" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SELECT_DEFAULT" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="[MENU URL]" Member="MENU_URL" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="[MENU ID]" Member="MENU_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="[CURRENCY ADJUST]" Member="CURRENCY_ADJUST" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="CURRENCY" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="[PC ADJUST]" Member="PC_ADJUST" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="WC" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="PERIOD" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
</Database>